//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCommon() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Resources.ResourceCommon", typeof(ResourceCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Agility 的本地化字符串。
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Average Damage inflicted on the trainer, Dps: {1:#.00}. 的本地化字符串。
        /// </summary>
        internal static string AverageDamageInflictedOnTheTrainerDps {
            get {
                return ResourceManager.GetString("AverageDamageInflictedOnTheTrainerDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bid Met 的本地化字符串。
        /// </summary>
        internal static string BidMet {
            get {
                return ResourceManager.GetString("BidMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired 的本地化字符串。
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed movement to Map {0} 的本地化字符串。
        /// </summary>
        internal static string FailedMovementToMap {
            get {
                return ResourceManager.GetString("FailedMovementToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed movement to Map {0} at {1}:{2} 的本地化字符串。
        /// </summary>
        internal static string FailedMovementToMapCord {
            get {
                return ResourceManager.GetString("FailedMovementToMapCord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed movement to Map {0}:[{1}] 的本地化字符串。
        /// </summary>
        internal static string FailedMovementToMapInstance {
            get {
                return ResourceManager.GetString("FailedMovementToMapInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed movement to Map {0}:[{1}] at {2}:{3} 的本地化字符串。
        /// </summary>
        internal static string FailedMovementToMapInstanceCord {
            get {
                return ResourceManager.GetString("FailedMovementToMapInstanceCord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Sale 的本地化字符串。
        /// </summary>
        internal static string ForSale {
            get {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has just expired from your equipment. 的本地化字符串。
        /// </summary>
        internal static string HasJustExpiredFromYourEquipment {
            get {
                return ResourceManager.GetString("HasJustExpiredFromYourEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has just expired from your inventory. 的本地化字符串。
        /// </summary>
        internal static string HasJustExpiredFromYourInventory {
            get {
                return ResourceManager.GetString("HasJustExpiredFromYourInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has just expired from your storage. 的本地化字符串。
        /// </summary>
        internal static string HasJustExpiredFromYourStorage {
            get {
                return ResourceManager.GetString("HasJustExpiredFromYourStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {3} inflicted {0} {1} Damage, Dps: {2:#.00}. 的本地化字符串。
        /// </summary>
        internal static string InflictedDamageDps {
            get {
                return ResourceManager.GetString("InflictedDamageDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} inflicted {0} Damage, Dps: {2:#.00}. 的本地化字符串。
        /// </summary>
        internal static string InflictedDamageDpsPoison {
            get {
                return ResourceManager.GetString("InflictedDamageDpsPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magic 的本地化字符串。
        /// </summary>
        internal static string Magic {
            get {
                return ResourceManager.GetString("Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magical Agility 的本地化字符串。
        /// </summary>
        internal static string MagicalAgility {
            get {
                return ResourceManager.GetString("MagicalAgility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map {0}:[{1}] could not be found 的本地化字符串。
        /// </summary>
        internal static string MapCouldNotBeFound {
            get {
                return ResourceManager.GetString("MapCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monster {0} x{1} has been spawned. 的本地化字符串。
        /// </summary>
        internal static string MonsterHasBeenSpawned {
            get {
                return ResourceManager.GetString("MonsterHasBeenSpawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moved to Map {0} 的本地化字符串。
        /// </summary>
        internal static string MovedToMap {
            get {
                return ResourceManager.GetString("MovedToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moved to Map {0} at {1}:{2 的本地化字符串。
        /// </summary>
        internal static string MovedToMapCord {
            get {
                return ResourceManager.GetString("MovedToMapCord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moved to Map {0}:[{1}] 的本地化字符串。
        /// </summary>
        internal static string MovedToMapInstance {
            get {
                return ResourceManager.GetString("MovedToMapInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moved to Map {0}:[{1}] at {2}:{3 的本地化字符串。
        /// </summary>
        internal static string MovedToMapInstanceCord {
            get {
                return ResourceManager.GetString("MovedToMapInstanceCord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Bid 的本地化字符串。
        /// </summary>
        internal static string NoBid {
            get {
                return ResourceManager.GetString("NoBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physical Agility 的本地化字符串。
        /// </summary>
        internal static string PhysicalAgility {
            get {
                return ResourceManager.GetString("PhysicalAgility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physicial 的本地化字符串。
        /// </summary>
        internal static string Physicial {
            get {
                return ResourceManager.GetString("Physicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sold 的本地化字符串。
        /// </summary>
        internal static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Someone has bid {1:#,##0} Gold for {0} 的本地化字符串。
        /// </summary>
        internal static string SomeoneHasBidGoldFor {
            get {
                return ResourceManager.GetString("SomeoneHasBidGoldFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The rental lock has been removed from {0} 的本地化字符串。
        /// </summary>
        internal static string TheRentalLockHasBeenRemovedFrom {
            get {
                return ResourceManager.GetString("TheRentalLockHasBeenRemovedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You 的本地化字符串。
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You bid {1:#,##0} Gold for {0} 的本地化字符串。
        /// </summary>
        internal static string YouBidGoldFor {
            get {
                return ResourceManager.GetString("YouBidGoldFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can already unequip a cursed item 的本地化字符串。
        /// </summary>
        internal static string YouCanAlreadyUnequipACursedItem {
            get {
                return ResourceManager.GetString("YouCanAlreadyUnequipACursedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot position move on this map 的本地化字符串。
        /// </summary>
        internal static string YouCannotPositionMoveOnThisMap {
            get {
                return ResourceManager.GetString("YouCannotPositionMoveOnThisMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot teleport for another {0} seconds 的本地化字符串。
        /// </summary>
        internal static string YouCannotTeleportForAnotherSeconds {
            get {
                return ResourceManager.GetString("YouCannotTeleportForAnotherSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can now unequip a cursed item. 的本地化字符串。
        /// </summary>
        internal static string YouCanNowUnequipACursedItem {
            get {
                return ResourceManager.GetString("YouCanNowUnequipACursedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your pet 的本地化字符串。
        /// </summary>
        internal static string YourPet {
            get {
                return ResourceManager.GetString("YourPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your pets poison 的本地化字符串。
        /// </summary>
        internal static string YourPetsPoison {
            get {
                return ResourceManager.GetString("YourPetsPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your poison 的本地化字符串。
        /// </summary>
        internal static string YourPoison {
            get {
                return ResourceManager.GetString("YourPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your poison stopped {0} regen, Dps: {1:#.00}. 的本地化字符串。
        /// </summary>
        internal static string YourPoisonStoppedRegenDps {
            get {
                return ResourceManager.GetString("YourPoisonStoppedRegenDps", resourceCulture);
            }
        }
    }
}
