//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMagic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMagic() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Resources.ResourceMagic", typeof(ResourceMagic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BladeAvalanche 的本地化字符串。
        /// </summary>
        internal static string BladeAvalanche {
            get {
                return ResourceManager.GetString("BladeAvalanche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CounterAttack 的本地化字符串。
        /// </summary>
        internal static string CounterAttack {
            get {
                return ResourceManager.GetString("CounterAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CrossHalfMoon 的本地化字符串。
        /// </summary>
        internal static string CrossHalfMoon {
            get {
                return ResourceManager.GetString("CrossHalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entrapment 的本地化字符串。
        /// </summary>
        internal static string Entrapment {
            get {
                return ResourceManager.GetString("Entrapment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fencing 的本地化字符串。
        /// </summary>
        internal static string Fencing {
            get {
                return ResourceManager.GetString("Fencing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FlamingSword 的本地化字符串。
        /// </summary>
        internal static string FlamingSword {
            get {
                return ResourceManager.GetString("FlamingSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fury 的本地化字符串。
        /// </summary>
        internal static string Fury {
            get {
                return ResourceManager.GetString("Fury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HalfMoon 的本地化字符串。
        /// </summary>
        internal static string HalfMoon {
            get {
                return ResourceManager.GetString("HalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImmortalSkin 的本地化字符串。
        /// </summary>
        internal static string ImmortalSkin {
            get {
                return ResourceManager.GetString("ImmortalSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LionRoar 的本地化字符串。
        /// </summary>
        internal static string LionRoar {
            get {
                return ResourceManager.GetString("LionRoar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProtectionField 的本地化字符串。
        /// </summary>
        internal static string ProtectionField {
            get {
                return ResourceManager.GetString("ProtectionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rage 的本地化字符串。
        /// </summary>
        internal static string Rage {
            get {
                return ResourceManager.GetString("Rage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShoulderDash 的本地化字符串。
        /// </summary>
        internal static string ShoulderDash {
            get {
                return ResourceManager.GetString("ShoulderDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SlashingBurst 的本地化字符串。
        /// </summary>
        internal static string SlashingBurst {
            get {
                return ResourceManager.GetString("SlashingBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slaying 的本地化字符串。
        /// </summary>
        internal static string Slaying {
            get {
                return ResourceManager.GetString("Slaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thrusting 的本地化字符串。
        /// </summary>
        internal static string Thrusting {
            get {
                return ResourceManager.GetString("Thrusting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TwinDrakeBlade 的本地化字符串。
        /// </summary>
        internal static string TwinDrakeBlade {
            get {
                return ResourceManager.GetString("TwinDrakeBlade", resourceCulture);
            }
        }
    }
}
