//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCommon() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Resources.ResourceCommon", typeof(ResourceCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Agility 的本地化字符串。
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A guild leader needs to be at least level {0} 的本地化字符串。
        /// </summary>
        internal static string AGuildLeaderNeedsToBeAtLeastLevel {
            get {
                return ResourceManager.GetString("AGuildLeaderNeedsToBeAtLeastLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A guild needs at least 2 leaders. 的本地化字符串。
        /// </summary>
        internal static string AGuildNeedsAtLeast1Leaders {
            get {
                return ResourceManager.GetString("AGuildNeedsAtLeast1Leaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already at war with this guild. 的本地化字符串。
        /// </summary>
        internal static string AlreadyAtWarWithThisGuild {
            get {
                return ResourceManager.GetString("AlreadyAtWarWithThisGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Average Damage inflicted on the trainer, Dps: {1:#.00}. 的本地化字符串。
        /// </summary>
        internal static string AverageDamageInflictedOnTheTrainerDps {
            get {
                return ResourceManager.GetString("AverageDamageInflictedOnTheTrainerDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bid Met 的本地化字符串。
        /// </summary>
        internal static string BidMet {
            get {
                return ResourceManager.GetString("BidMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlackStone 的本地化字符串。
        /// </summary>
        internal static string BlackStone {
            get {
                return ResourceManager.GetString("BlackStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buff already obtained. 的本地化字符串。
        /// </summary>
        internal static string BuffAlreadyObtained {
            get {
                return ResourceManager.GetString("BuffAlreadyObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buff does not excist. 的本地化字符串。
        /// </summary>
        internal static string BuffDoesNotExcist {
            get {
                return ResourceManager.GetString("BuffDoesNotExcist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buff not obtained. 的本地化字符串。
        /// </summary>
        internal static string BuffNotObtained {
            get {
                return ResourceManager.GetString("BuffNotObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add yourself 的本地化字符串。
        /// </summary>
        internal static string CannotAddYourself {
            get {
                return ResourceManager.GetString("CannotAddYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot go to war with your own guild. 的本地化字符串。
        /// </summary>
        internal static string CannotGoToWarWithYourOwnGuild {
            get {
                return ResourceManager.GetString("CannotGoToWarWithYourOwnGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot trade when dead 的本地化字符串。
        /// </summary>
        internal static string CannotTradeWhenDead {
            get {
                return ResourceManager.GetString("CannotTradeWhenDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t find anybody by the name {0}. 的本地化字符串。
        /// </summary>
        internal static string CaNotFindAnybodyByTheName {
            get {
                return ResourceManager.GetString("CaNotFindAnybodyByTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congratulations, you&apos;re now married to {0}. 的本地化字符串。
        /// </summary>
        internal static string CongratulationsYouAreNowMarriedTo {
            get {
                return ResourceManager.GetString("CongratulationsYouAreNowMarriedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congratulations, your {0} now has +{1} extra DC. 的本地化字符串。
        /// </summary>
        internal static string CongratulationsYourNowHasExtraDC {
            get {
                return ResourceManager.GetString("CongratulationsYourNowHasExtraDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congratulations, your {0} now has +{1} extra MC. 的本地化字符串。
        /// </summary>
        internal static string CongratulationsYourNowHasExtraMC {
            get {
                return ResourceManager.GetString("CongratulationsYourNowHasExtraMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congratulations, your {0} now has +{1} extra SC. 的本地化字符串。
        /// </summary>
        internal static string CongratulationsYourNowHasExtraSC {
            get {
                return ResourceManager.GetString("CongratulationsYourNowHasExtraSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find guild {0}. 的本地化字符串。
        /// </summary>
        internal static string CouldNotFindGuild {
            get {
                return ResourceManager.GetString("CouldNotFindGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creature {0} has been dismissed. 的本地化字符串。
        /// </summary>
        internal static string CreatureHasBeenDismissed {
            get {
                return ResourceManager.GetString("CreatureHasBeenDismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creature {0} has been released. 的本地化字符串。
        /// </summary>
        internal static string CreatureHasBeenReleased {
            get {
                return ResourceManager.GetString("CreatureHasBeenReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creature {0} has been summoned. 的本地化字符串。
        /// </summary>
        internal static string CreatureHasBeenSummoned {
            get {
                return ResourceManager.GetString("CreatureHasBeenSummoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creature {0} has expired. 的本地化字符串。
        /// </summary>
        internal static string CreatureHasExpired {
            get {
                return ResourceManager.GetString("CreatureHasExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} doesn&apos;t need to be checked as it hasn&apos;t been refined yet. 的本地化字符串。
        /// </summary>
        internal static string DoesNotNeedToBeCheckedAsItHasNotBeenRefinedYet {
            get {
                return ResourceManager.GetString("DoesNotNeedToBeCheckedAsItHasNotBeenRefinedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired 的本地化字符串。
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed movement to Map {0} 的本地化字符串。
        /// </summary>
        internal static string FailedMovementToMap {
            get {
                return ResourceManager.GetString("FailedMovementToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed movement to Map {0} at {1}:{2} 的本地化字符串。
        /// </summary>
        internal static string FailedMovementToMapCord {
            get {
                return ResourceManager.GetString("FailedMovementToMapCord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed movement to Map {0}:[{1}] 的本地化字符串。
        /// </summary>
        internal static string FailedMovementToMapInstance {
            get {
                return ResourceManager.GetString("FailedMovementToMapInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed movement to Map {0}:[{1}] at {2}:{3} 的本地化字符串。
        /// </summary>
        internal static string FailedMovementToMapInstanceCord {
            get {
                return ResourceManager.GetString("FailedMovementToMapInstanceCord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Sale 的本地化字符串。
        /// </summary>
        internal static string ForSale {
            get {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has just expired from your equipment. 的本地化字符串。
        /// </summary>
        internal static string HasJustExpiredFromYourEquipment {
            get {
                return ResourceManager.GetString("HasJustExpiredFromYourEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has just expired from your inventory. 的本地化字符串。
        /// </summary>
        internal static string HasJustExpiredFromYourInventory {
            get {
                return ResourceManager.GetString("HasJustExpiredFromYourInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has just expired from your storage. 的本地化字符串。
        /// </summary>
        internal static string HasJustExpiredFromYourStorage {
            get {
                return ResourceManager.GetString("HasJustExpiredFromYourStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has started a war 的本地化字符串。
        /// </summary>
        internal static string HasStartedAWar {
            get {
                return ResourceManager.GetString("HasStartedAWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I&apos;m starving!!. 的本地化字符串。
        /// </summary>
        internal static string ImStarving {
            get {
                return ResourceManager.GetString("ImStarving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {3} inflicted {0} {1} Damage, Dps: {2:#.00}. 的本地化字符串。
        /// </summary>
        internal static string InflictedDamageDps {
            get {
                return ResourceManager.GetString("InflictedDamageDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} inflicted {0} Damage, Dps: {2:#.00}. 的本地化字符串。
        /// </summary>
        internal static string InflictedDamageDpsPoison {
            get {
                return ResourceManager.GetString("InflictedDamageDpsPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leader 的本地化字符串。
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magic 的本地化字符串。
        /// </summary>
        internal static string Magic {
            get {
                return ResourceManager.GetString("Magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magical Agility 的本地化字符串。
        /// </summary>
        internal static string MagicalAgility {
            get {
                return ResourceManager.GetString("MagicalAgility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map {0}:[{1}] could not be found 的本地化字符串。
        /// </summary>
        internal static string MapCouldNotBeFound {
            get {
                return ResourceManager.GetString("MapCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Members 的本地化字符串。
        /// </summary>
        internal static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monster {0} x{1} has been spawned. 的本地化字符串。
        /// </summary>
        internal static string MonsterHasBeenSpawned {
            get {
                return ResourceManager.GetString("MonsterHasBeenSpawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moved to Map {0} 的本地化字符串。
        /// </summary>
        internal static string MovedToMap {
            get {
                return ResourceManager.GetString("MovedToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moved to Map {0} at {1}:{2 的本地化字符串。
        /// </summary>
        internal static string MovedToMapCord {
            get {
                return ResourceManager.GetString("MovedToMapCord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moved to Map {0}:[{1}] 的本地化字符串。
        /// </summary>
        internal static string MovedToMapInstance {
            get {
                return ResourceManager.GetString("MovedToMapInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moved to Map {0}:[{1}] at {2}:{3 的本地化字符串。
        /// </summary>
        internal static string MovedToMapInstanceCord {
            get {
                return ResourceManager.GetString("MovedToMapInstanceCord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Bid 的本地化字符串。
        /// </summary>
        internal static string NoBid {
            get {
                return ResourceManager.GetString("NoBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more space. 的本地化字符串。
        /// </summary>
        internal static string NoMoreSpace {
            get {
                return ResourceManager.GetString("NoMoreSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough funds in guild bank. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughFundsInGuildBank {
            get {
                return ResourceManager.GetString("NotEnoughFundsInGuildBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough gold. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughGold {
            get {
                return ResourceManager.GetString("NotEnoughGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physical Agility 的本地化字符串。
        /// </summary>
        internal static string PhysicalAgility {
            get {
                return ResourceManager.GetString("PhysicalAgility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Physicial 的本地化字符串。
        /// </summary>
        internal static string Physicial {
            get {
                return ResourceManager.GetString("Physicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player already added 的本地化字符串。
        /// </summary>
        internal static string PlayerAlreadyAdded {
            get {
                return ResourceManager.GetString("PlayerAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player doesn&apos;t exist 的本地化字符串。
        /// </summary>
        internal static string PlayerDoesNotExist {
            get {
                return ResourceManager.GetString("PlayerDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} already has a trade invitation. 的本地化字符串。
        /// </summary>
        internal static string PlayerWhoAlreadyHasATradeInvitation {
            get {
                return ResourceManager.GetString("PlayerWhoAlreadyHasATradeInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} has refused to trade. 的本地化字符串。
        /// </summary>
        internal static string PlayerWhoHasRefusedToTrade {
            get {
                return ResourceManager.GetString("PlayerWhoHasRefusedToTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} is already trading. 的本地化字符串。
        /// </summary>
        internal static string PlayerWhoIsAlreadyTrading {
            get {
                return ResourceManager.GetString("PlayerWhoIsAlreadyTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} is not allowing trade at the moment. 的本地化字符串。
        /// </summary>
        internal static string PlayerWhoIsNotAllowingTradeAtTheMoment {
            get {
                return ResourceManager.GetString("PlayerWhoIsNotAllowingTradeAtTheMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} is not within trading range. 的本地化字符串。
        /// </summary>
        internal static string PlayerWhoIsNotWithinTradingRange {
            get {
                return ResourceManager.GetString("PlayerWhoIsNotWithinTradingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player {0} is waiting for you to confirm trade. 的本地化字符串。
        /// </summary>
        internal static string PlayerWhoIsWaitingForYouToConfirmTrade {
            get {
                return ResourceManager.GetString("PlayerWhoIsWaitingForYouToConfirmTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rank 的本地化字符串。
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rank name too short! 的本地化字符串。
        /// </summary>
        internal static string RankNameToShort {
            get {
                return ResourceManager.GetString("RankNameToShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rank not found! 的本地化字符串。
        /// </summary>
        internal static string RankNotFound {
            get {
                return ResourceManager.GetString("RankNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Request Sent. 的本地化字符串。
        /// </summary>
        internal static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sold 的本地化字符串。
        /// </summary>
        internal static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Someone has bid {1:#,##0} Gold for {0} 的本地化字符串。
        /// </summary>
        internal static string SomeoneHasBidGoldFor {
            get {
                return ResourceManager.GetString("SomeoneHasBidGoldFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: SummonedCreature no longer exists?!?. {1} 的本地化字符串。
        /// </summary>
        internal static string SummonedCreatureNoLongerExists {
            get {
                return ResourceManager.GetString("SummonedCreatureNoLongerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The person you&apos;re trying to propose to isn&apos;t allowing marriage requests. 的本地化字符串。
        /// </summary>
        internal static string ThePersonYouAreTryingToProposeToIsNotAllowingMarriageRequests {
            get {
                return ResourceManager.GetString("ThePersonYouAreTryingToProposeToIsNotAllowingMarriageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There isn&apos;t room in your bag for your {0}, make some space and try again. 的本地化字符串。
        /// </summary>
        internal static string ThereIsNotRoomInYourBagForYourMakeSomeSpaceAndTryAgain {
            get {
                return ResourceManager.GetString("ThereIsNotRoomInYourBagForYourMakeSomeSpaceAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The rental lock has been removed from {0} 的本地化字符串。
        /// </summary>
        internal static string TheRentalLockHasBeenRemovedFrom {
            get {
                return ResourceManager.GetString("TheRentalLockHasBeenRemovedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}d {1}h {2:D2}m 的本地化字符串。
        /// </summary>
        internal static string TimeDayHourMinutes {
            get {
                return ResourceManager.GetString("TimeDayHourMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}h {1:D2}m 的本地化字符串。
        /// </summary>
        internal static string TimeHourMinutes {
            get {
                return ResourceManager.GetString("TimeHourMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}m 的本地化字符串。
        /// </summary>
        internal static string TimeMinutes {
            get {
                return ResourceManager.GetString("TimeMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}s 的本地化字符串。
        /// </summary>
        internal static string TimeSeconds {
            get {
                return ResourceManager.GetString("TimeSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too heavy to get back. 的本地化字符串。
        /// </summary>
        internal static string TooHeavyToGetBack {
            get {
                return ResourceManager.GetString("TooHeavyToGetBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trade from {0} to {1} 的本地化字符串。
        /// </summary>
        internal static string TradeFromTo {
            get {
                return ResourceManager.GetString("TradeFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trade successful. 的本地化字符串。
        /// </summary>
        internal static string TradeSuccessful {
            get {
                return ResourceManager.GetString("TradeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trading partner cannot accept all items. 的本地化字符串。
        /// </summary>
        internal static string TradingPartnerCannotAcceptAllItems {
            get {
                return ResourceManager.GetString("TradingPartnerCannotAcceptAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trading partner cannot accept any more gold. 的本地化字符串。
        /// </summary>
        internal static string TradingPartnerCannotAcceptAnyMoreGold {
            get {
                return ResourceManager.GetString("TradingPartnerCannotAcceptAnyMoreGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to accept all items. 的本地化字符串。
        /// </summary>
        internal static string UnableToAcceptAllItems {
            get {
                return ResourceManager.GetString("UnableToAcceptAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to accept any more gold. 的本地化字符串。
        /// </summary>
        internal static string UnableToAcceptAnyMoreGold {
            get {
                return ResourceManager.GetString("UnableToAcceptAnyMoreGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 War ended with {0}. 的本地化字符串。
        /// </summary>
        internal static string WarEndedWith {
            get {
                return ResourceManager.GetString("WarEndedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} already has a marriage invitation. 的本地化字符串。
        /// </summary>
        internal static string WhoAlreadyHasAMarriageInvitation {
            get {
                return ResourceManager.GetString("WhoAlreadyHasAMarriageInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} already has a Mentor. 的本地化字符串。
        /// </summary>
        internal static string WhoAlreadyHasAMentor {
            get {
                return ResourceManager.GetString("WhoAlreadyHasAMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can&apos;t get married again yet, there is a {1} day cooldown after divorce 的本地化字符串。
        /// </summary>
        internal static string WhoCanNotGetMarriedAgainYetThereIsADayCooldownAfterDivorce {
            get {
                return ResourceManager.GetString("WhoCanNotGetMarriedAgainYetThereIsADayCooldownAfterDivorce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can&apos;t start another Mentorship yet. 的本地化字符串。
        /// </summary>
        internal static string WhoCaNotStartAnotherMentorshipYet {
            get {
                return ResourceManager.GetString("WhoCaNotStartAnotherMentorshipYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has come online. 的本地化字符串。
        /// </summary>
        internal static string WhoHasComeOnline {
            get {
                return ResourceManager.GetString("WhoHasComeOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has gone offline. 的本地化字符串。
        /// </summary>
        internal static string WhoHasGoneOffline {
            get {
                return ResourceManager.GetString("WhoHasGoneOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has refused to divorce you. 的本地化字符串。
        /// </summary>
        internal static string WhoHasRefusedToDivorceYou {
            get {
                return ResourceManager.GetString("WhoHasRefusedToDivorceYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has refused to marry you. 的本地化字符串。
        /// </summary>
        internal static string WhoHasRefusedToMarryYou {
            get {
                return ResourceManager.GetString("WhoHasRefusedToMarryYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has refused to Mentor you. 的本地化字符串。
        /// </summary>
        internal static string WhoHasRefusedToMentorYou {
            get {
                return ResourceManager.GetString("WhoHasRefusedToMentorYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is already a Mentor. 的本地化字符串。
        /// </summary>
        internal static string WhoIsAlreadyAMentor {
            get {
                return ResourceManager.GetString("WhoIsAlreadyAMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is already married. 的本地化字符串。
        /// </summary>
        internal static string WhoIsAlreadyMarried {
            get {
                return ResourceManager.GetString("WhoIsAlreadyMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is married but couldn&apos;t find marriage ID {1} 的本地化字符串。
        /// </summary>
        internal static string WhoIsMarriedButCouldNotFindMarriageID {
            get {
                return ResourceManager.GetString("WhoIsMarriedButCouldNotFindMarriageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is mentored but couldn&apos;t find mentor ID {1} 的本地化字符串。
        /// </summary>
        internal static string WhoIsMentoredButCouldNotFindMentorID {
            get {
                return ResourceManager.GetString("WhoIsMentoredButCouldNotFindMentorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is no longer online. 的本地化字符串。
        /// </summary>
        internal static string WhoIsNoLongerOnline {
            get {
                return ResourceManager.GetString("WhoIsNoLongerOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not allowing Mentor requests. 的本地化字符串。
        /// </summary>
        internal static string WhoIsNotAllowingMentorRequests {
            get {
                return ResourceManager.GetString("WhoIsNotAllowingMentorRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not within divorce range. 的本地化字符串。
        /// </summary>
        internal static string WhoIsNotWithinDivorceRange {
            get {
                return ResourceManager.GetString("WhoIsNotWithinDivorceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not within marriage range. 的本地化字符串。
        /// </summary>
        internal static string WhoIsNotWithinMarriageRange {
            get {
                return ResourceManager.GetString("WhoIsNotWithinMarriageRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You 的本地化字符串。
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You already have a Mentor. 的本地化字符串。
        /// </summary>
        internal static string YouAlreadyHaveAMentor {
            get {
                return ResourceManager.GetString("YouAlreadyHaveAMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You already have a Student. 的本地化字符串。
        /// </summary>
        internal static string YouAlreadyHaveAStudent {
            get {
                return ResourceManager.GetString("YouAlreadyHaveAStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already married. 的本地化字符串。
        /// </summary>
        internal static string YouAreAlreadyMarried {
            get {
                return ResourceManager.GetString("YouAreAlreadyMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already trading. 的本地化字符串。
        /// </summary>
        internal static string YouAreAlreadyTrading {
            get {
                return ResourceManager.GetString("YouAreAlreadyTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re already wearing a Wedding Ring. 的本地化字符串。
        /// </summary>
        internal static string YouAreAlreadyWearingAWeddingRing {
            get {
                return ResourceManager.GetString("YouAreAlreadyWearingAWeddingRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not allowed to change ranks! 的本地化字符串。
        /// </summary>
        internal static string YouAreNotAllowedToChangeRanks {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToChangeRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You aren&apos;t currently refining any items. 的本地化字符串。
        /// </summary>
        internal static string YouAreNotCurrentlyRefiningAnyItems {
            get {
                return ResourceManager.GetString("YouAreNotCurrentlyRefiningAnyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re not married. 的本地化字符串。
        /// </summary>
        internal static string YouAreNotMarried {
            get {
                return ResourceManager.GetString("YouAreNotMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You aren&apos;t married so you don&apos;t require a divorce. 的本地化字符串。
        /// </summary>
        internal static string YouAreNotMarriedSoYouDoNotRequireADivorce {
            get {
                return ResourceManager.GetString("YouAreNotMarriedSoYouDoNotRequireADivorce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You aren&apos;t married to {0} 的本地化字符串。
        /// </summary>
        internal static string YouAreNotMarriedTo {
            get {
                return ResourceManager.GetString("YouAreNotMarriedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You aren&apos;t wearing a ring to upgrade. 的本地化字符串。
        /// </summary>
        internal static string YouAreNotWearingARingToUpgrade {
            get {
                return ResourceManager.GetString("YouAreNotWearingARingToUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You arn&apos;t wearing a Wedding Ring to upgrade. 的本地化字符串。
        /// </summary>
        internal static string YouAreNotWearingAWeddingRingToUpgrade {
            get {
                return ResourceManager.GetString("YouAreNotWearingAWeddingRingToUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now allowing marriage requests. 的本地化字符串。
        /// </summary>
        internal static string YouAreNowAllowingMarriageRequests {
            get {
                return ResourceManager.GetString("YouAreNowAllowingMarriageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now allowing recall from lover. 的本地化字符串。
        /// </summary>
        internal static string YouAreNowAllowingRecallFromLover {
            get {
                return ResourceManager.GetString("YouAreNowAllowingRecallFromLover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now being Mentored by {0}. 的本地化字符串。
        /// </summary>
        internal static string YouAreNowBeingMentoredBy {
            get {
                return ResourceManager.GetString("YouAreNowBeingMentoredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now blocking marriage requests. 的本地化字符串。
        /// </summary>
        internal static string YouAreNowBlockingMarriageRequests {
            get {
                return ResourceManager.GetString("YouAreNowBlockingMarriageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now blocking recall from lover. 的本地化字符串。
        /// </summary>
        internal static string YouAreNowBlockingRecallFromLover {
            get {
                return ResourceManager.GetString("YouAreNowBlockingRecallFromLover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now divorced 的本地化字符串。
        /// </summary>
        internal static string YouAreNowDivorced {
            get {
                return ResourceManager.GetString("YouAreNowDivorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re now the Mentor of {0}. 的本地化字符串。
        /// </summary>
        internal static string YouAreNowTheMentorOfWhom {
            get {
                return ResourceManager.GetString("YouAreNowTheMentorOfWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You bid {1:#,##0} Gold for {0} 的本地化字符串。
        /// </summary>
        internal static string YouBidGoldFor {
            get {
                return ResourceManager.GetString("YouBidGoldFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can already unequip a cursed item 的本地化字符串。
        /// </summary>
        internal static string YouCanAlreadyUnequipACursedItem {
            get {
                return ResourceManager.GetString("YouCanAlreadyUnequipACursedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot change the options of your own rank! 的本地化字符串。
        /// </summary>
        internal static string YouCannotChangeTheOptionsOfYourOwnRank {
            get {
                return ResourceManager.GetString("YouCannotChangeTheOptionsOfYourOwnRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t equip the item you&apos;re trying to use. 的本地化字符串。
        /// </summary>
        internal static string YouCanNotEquipTheItemYouAreTryingToUse {
            get {
                return ResourceManager.GetString("YouCanNotEquipTheItemYouAreTryingToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t get married again yet, there is a {0} day cooldown after a divorce. 的本地化字符串。
        /// </summary>
        internal static string YouCanNotGetMarriedAgainYetThereIsADayCooldownAfterADivorce {
            get {
                return ResourceManager.GetString("YouCanNotGetMarriedAgainYetThereIsADayCooldownAfterADivorce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot have anymore ranks. 的本地化字符串。
        /// </summary>
        internal static string YouCannotHaveAnymoreRanks {
            get {
                return ResourceManager.GetString("YouCannotHaveAnymoreRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot leave the guild when you&apos;re leader. 的本地化字符串。
        /// </summary>
        internal static string YouCannotLeaveTheGuildWhenYouAreLeader {
            get {
                return ResourceManager.GetString("YouCannotLeaveTheGuildWhenYouAreLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t perform a marriage with a dead player. 的本地化字符串。
        /// </summary>
        internal static string YouCanNotPerformAMarriageWithADeadPlayer {
            get {
                return ResourceManager.GetString("YouCanNotPerformAMarriageWithADeadPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot position move on this map 的本地化字符串。
        /// </summary>
        internal static string YouCannotPositionMoveOnThisMap {
            get {
                return ResourceManager.GetString("YouCannotPositionMoveOnThisMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t replace a Wedding Ring with this item. 的本地化字符串。
        /// </summary>
        internal static string YouCanNotReplaceAWeddingRingWithThisItem {
            get {
                return ResourceManager.GetString("YouCanNotReplaceAWeddingRingWithThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot ride here without a bridle 的本地化字符串。
        /// </summary>
        internal static string YouCannotRideHereWithoutABridle {
            get {
                return ResourceManager.GetString("YouCannotRideHereWithoutABridle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot ride on this map 的本地化字符串。
        /// </summary>
        internal static string YouCannotRideOnThisMap {
            get {
                return ResourceManager.GetString("YouCannotRideOnThisMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot teleport for another {0} seconds 的本地化字符串。
        /// </summary>
        internal static string YouCannotTeleportForAnotherSeconds {
            get {
                return ResourceManager.GetString("YouCannotTeleportForAnotherSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot trade with your self. 的本地化字符串。
        /// </summary>
        internal static string YouCanNotTradeWithYourSelf {
            get {
                return ResourceManager.GetString("YouCanNotTradeWithYourSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use this type of ring. 的本地化字符串。
        /// </summary>
        internal static string YouCanNotUseThisTypeOfRing {
            get {
                return ResourceManager.GetString("YouCanNotUseThisTypeOfRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can now unequip a cursed item. 的本地化字符串。
        /// </summary>
        internal static string YouCanNowUnequipACursedItem {
            get {
                return ResourceManager.GetString("YouCanNowUnequipACursedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only be mentored by someone of the same Class. 的本地化字符串。
        /// </summary>
        internal static string YouCanOnlyBeMentoredBySomeoneOfTheSameClass {
            get {
                return ResourceManager.GetString("YouCanOnlyBeMentoredBySomeoneOfTheSameClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only be mentored by someone who at least {0} level(s) above you. 的本地化字符串。
        /// </summary>
        internal static string YouCanOnlyBeMentoredBySomeoneWhoAtLeastXlevelsAboveYou {
            get {
                return ResourceManager.GetString("YouCanOnlyBeMentoredBySomeoneWhoAtLeastXlevelsAboveYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only mentor someone of the same Class. 的本地化字符串。
        /// </summary>
        internal static string YouCanOnlyMentorSomeoneOfTheSameClass {
            get {
                return ResourceManager.GetString("YouCanOnlyMentorSomeoneOfTheSameClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only mentor someone who at least {0} level(s) below you. 的本地化字符串。
        /// </summary>
        internal static string YouCanOnlyMentorSomeoneWhoAtLeastXlevelsBbelowYou {
            get {
                return ResourceManager.GetString("YouCanOnlyMentorSomeoneWhoAtLeastXlevelsBbelowYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t divorce a dead player. 的本地化字符串。
        /// </summary>
        internal static string YouCaNotDivorceADeadPlayer {
            get {
                return ResourceManager.GetString("YouCaNotDivorceADeadPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t divorce yourself. 的本地化字符串。
        /// </summary>
        internal static string YouCaNotDivorceYourself {
            get {
                return ResourceManager.GetString("YouCaNotDivorceYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t Mentor yourself. 的本地化字符串。
        /// </summary>
        internal static string YouCaNotMentorYourself {
            get {
                return ResourceManager.GetString("YouCaNotMentorYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t start a new Mentorship yet. 的本地化字符串。
        /// </summary>
        internal static string YouCaNotStartANewMentorshipYet {
            get {
                return ResourceManager.GetString("YouCaNotStartANewMentorshipYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cant marry yourself. 的本地化字符串。
        /// </summary>
        internal static string YouCantMarryYourself {
            get {
                return ResourceManager.GetString("YouCantMarryYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have enough gold to refine your {0}. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveEnoughGoldToRefineYour {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughGoldToRefineYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have enough gold to replace your Wedding Ring. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveEnoughGoldToReplaceYourWeddingRing {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughGoldToReplaceYourWeddingRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have the correct guild rank. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveTheCorrectGuildRank {
            get {
                return ResourceManager.GetString("YouDoNotHaveTheCorrectGuildRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have been removed from your guild. 的本地化字符串。
        /// </summary>
        internal static string YouHaveBeenRemovedFromYourGuild {
            get {
                return ResourceManager.GetString("YouHaveBeenRemovedFromYourGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;ve just been forcefully divorced 的本地化字符串。
        /// </summary>
        internal static string YouHaveJustBeenForcefullyDivorced {
            get {
                return ResourceManager.GetString("YouHaveJustBeenForcefullyDivorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have left your guild. 的本地化字符串。
        /// </summary>
        internal static string YouHaveLeftYourGuild {
            get {
                return ResourceManager.GetString("YouHaveLeftYourGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must be a leader to start a war. 的本地化字符串。
        /// </summary>
        internal static string YouMustBeALeaderToStartAWar {
            get {
                return ResourceManager.GetString("YouMustBeALeaderToStartAWar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must have a saddle to ride your mount 的本地化字符串。
        /// </summary>
        internal static string YouMustHaveASaddleToRideYourMount {
            get {
                return ResourceManager.GetString("YouMustHaveASaddleToRideYourMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need a hook. 的本地化字符串。
        /// </summary>
        internal static string YouNeedAHook {
            get {
                return ResourceManager.GetString("YouNeedAHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need at least 1 leader online. 的本地化字符串。
        /// </summary>
        internal static string YouNeedAtLeast1LeaderOnline {
            get {
                return ResourceManager.GetString("YouNeedAtLeast1LeaderOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need bait. 的本地化字符串。
        /// </summary>
        internal static string YouNeedBait {
            get {
                return ResourceManager.GetString("YouNeedBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to be at least level {0} to get married. 的本地化字符串。
        /// </summary>
        internal static string YouNeedToBeAtLeastLevelToGetMarried {
            get {
                return ResourceManager.GetString("YouNeedToBeAtLeastLevelToGetMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to be facing a player to request a marriage. 的本地化字符串。
        /// </summary>
        internal static string YouNeedToBeFacingAPlayerToRequestAMarriage {
            get {
                return ResourceManager.GetString("YouNeedToBeFacingAPlayerToRequestAMarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to be facing each other to perform a marriage. 的本地化字符串。
        /// </summary>
        internal static string YouNeedToBeFacingEachOtherToPerformAMarriage {
            get {
                return ResourceManager.GetString("YouNeedToBeFacingEachOtherToPerformAMarriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to be facing your lover to divorce them. 的本地化字符串。
        /// </summary>
        internal static string YouNeedToBeFacingYourLoverToDivorceThem {
            get {
                return ResourceManager.GetString("YouNeedToBeFacingYourLoverToDivorceThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to be married to make a Wedding Ring. 的本地化字符串。
        /// </summary>
        internal static string YouNeedToBeMarriedToMakeAWeddingRing {
            get {
                return ResourceManager.GetString("YouNeedToBeMarriedToMakeAWeddingRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You need to wear a ring on your left finger to make a Wedding Ring. 的本地化字符串。
        /// </summary>
        internal static string YouNeedToWearARingOnYourLeftFingerToMakeAWeddingRing {
            get {
                return ResourceManager.GetString("YouNeedToWearARingOnYourLeftFingerToMakeAWeddingRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You now have a {0} day cooldown on starting a new Mentorship. 的本地化字符串。
        /// </summary>
        internal static string YouNowHaveAXDayCooldownOnStartingANewMentorship {
            get {
                return ResourceManager.GetString("YouNowHaveAXDayCooldownOnStartingANewMentorship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your {0} can&apos;t be refined. 的本地化字符串。
        /// </summary>
        internal static string YourCaNotBeRefined {
            get {
                return ResourceManager.GetString("YourCaNotBeRefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your fish got away! 的本地化字符串。
        /// </summary>
        internal static string YourFishGotAway {
            get {
                return ResourceManager.GetString("YourFishGotAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your {0} is now being refined, please check back in {1} minute(s). 的本地化字符串。
        /// </summary>
        internal static string YourIsNowBeingRefinedPleaseCheckBackInMinute {
            get {
                return ResourceManager.GetString("YourIsNowBeingRefinedPleaseCheckBackInMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your {0} is too heavy to get back, try again after reducing your bag weight. 的本地化字符串。
        /// </summary>
        internal static string YourIsTooHeavyToGetBackTryAgainAfterReducingYourBagWeight {
            get {
                return ResourceManager.GetString("YourIsTooHeavyToGetBackTryAgainAfterReducingYourBagWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your item has been returned to you. 的本地化字符串。
        /// </summary>
        internal static string YourItemHasBeenReturnedToYou {
            get {
                return ResourceManager.GetString("YourItemHasBeenReturnedToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your lover needs to be at least level {0} to get married. 的本地化字符串。
        /// </summary>
        internal static string YourLoverNeedsToBeAtLeastLevelToGetMarried {
            get {
                return ResourceManager.GetString("YourLoverNeedsToBeAtLeastLevelToGetMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Mentorship has now expired. 的本地化字符串。
        /// </summary>
        internal static string YourMentorshipHasNowExpired {
            get {
                return ResourceManager.GetString("YourMentorshipHasNowExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your {0} needs to be checked before you can attempt to refine it again. 的本地化字符串。
        /// </summary>
        internal static string YourNeedsToBeCheckedBeforeYouCanAttemptToRefineItAgain {
            get {
                return ResourceManager.GetString("YourNeedsToBeCheckedBeforeYouCanAttemptToRefineItAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your pet 的本地化字符串。
        /// </summary>
        internal static string YourPet {
            get {
                return ResourceManager.GetString("YourPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your pet has produced x1 BlackStone which couldn&apos;t be added to your inventory. 的本地化字符串。
        /// </summary>
        internal static string YourPetHasProducedX1BlackStoneWhichCouldNotBeAddedToYourInventory {
            get {
                return ResourceManager.GetString("YourPetHasProducedX1BlackStoneWhichCouldNotBeAddedToYourInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your pets poison 的本地化字符串。
        /// </summary>
        internal static string YourPetsPoison {
            get {
                return ResourceManager.GetString("YourPetsPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your poison 的本地化字符串。
        /// </summary>
        internal static string YourPoison {
            get {
                return ResourceManager.GetString("YourPoison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your poison stopped {0} regen, Dps: {1:#.00}. 的本地化字符串。
        /// </summary>
        internal static string YourPoisonStoppedRegenDps {
            get {
                return ResourceManager.GetString("YourPoisonStoppedRegenDps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your rank is not adequate. 的本地化字符串。
        /// </summary>
        internal static string YourRankIsNotAdequate {
            get {
                return ResourceManager.GetString("YourRankIsNotAdequate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your {0} smashed into a thousand pieces upon testing. 的本地化字符串。
        /// </summary>
        internal static string YourSmashedIntoAThousandPiecesUponTesting {
            get {
                return ResourceManager.GetString("YourSmashedIntoAThousandPiecesUponTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your {0} will be ready to collect in {1} minute(s). 的本地化字符串。
        /// </summary>
        internal static string YourWillBeReadyToCollectInMinutes {
            get {
                return ResourceManager.GetString("YourWillBeReadyToCollectInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You started a war with {0}. 的本地化字符串。
        /// </summary>
        internal static string YouStartedAWarWith {
            get {
                return ResourceManager.GetString("YouStartedAWarWith", resourceCulture);
            }
        }
    }
}
