//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCommon() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Resources.ResourceCommon", typeof(ResourceCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bid Met 的本地化字符串。
        /// </summary>
        internal static string BidMet {
            get {
                return ResourceManager.GetString("BidMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired 的本地化字符串。
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Sale 的本地化字符串。
        /// </summary>
        internal static string ForSale {
            get {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has just expired from your equipment. 的本地化字符串。
        /// </summary>
        internal static string HasJustExpiredFromYourEquipment {
            get {
                return ResourceManager.GetString("HasJustExpiredFromYourEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has just expired from your inventory. 的本地化字符串。
        /// </summary>
        internal static string HasJustExpiredFromYourInventory {
            get {
                return ResourceManager.GetString("HasJustExpiredFromYourInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 has just expired from your storage. 的本地化字符串。
        /// </summary>
        internal static string HasJustExpiredFromYourStorage {
            get {
                return ResourceManager.GetString("HasJustExpiredFromYourStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monster {0} x{1} has been spawned. 的本地化字符串。
        /// </summary>
        internal static string MonsterHasBeenSpawned {
            get {
                return ResourceManager.GetString("MonsterHasBeenSpawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Bid 的本地化字符串。
        /// </summary>
        internal static string NoBid {
            get {
                return ResourceManager.GetString("NoBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sold 的本地化字符串。
        /// </summary>
        internal static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Someone has bid {1:#,##0} Gold for {0} 的本地化字符串。
        /// </summary>
        internal static string SomeoneHasBidGoldFor {
            get {
                return ResourceManager.GetString("SomeoneHasBidGoldFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The rental lock has been removed from {0} 的本地化字符串。
        /// </summary>
        internal static string TheRentalLockHasBeenRemovedFrom {
            get {
                return ResourceManager.GetString("TheRentalLockHasBeenRemovedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You bid {1:#,##0} Gold for {0} 的本地化字符串。
        /// </summary>
        internal static string YouBidGoldFor {
            get {
                return ResourceManager.GetString("YouBidGoldFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can already unequip a cursed item 的本地化字符串。
        /// </summary>
        internal static string YouCanAlreadyUnequipACursedItem {
            get {
                return ResourceManager.GetString("YouCanAlreadyUnequipACursedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can now unequip a cursed item. 的本地化字符串。
        /// </summary>
        internal static string YouCanNowUnequipACursedItem {
            get {
                return ResourceManager.GetString("YouCanNowUnequipACursedItem", resourceCulture);
            }
        }
    }
}
