//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceHelpDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceHelpDialog() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceHelpDialog", typeof(ResourceHelpDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Attacking 的本地化字符串。
        /// </summary>
        internal static string Attacking {
            get {
                return ResourceManager.GetString("Attacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat Shortcuts 的本地化字符串。
        /// </summary>
        internal static string ChatShortcuts {
            get {
                return ResourceManager.GetString("ChatShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chatting 的本地化字符串。
        /// </summary>
        internal static string Chatting {
            get {
                return ResourceManager.GetString("Chatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collecting Items 的本地化字符串。
        /// </summary>
        internal static string CollectingItems {
            get {
                return ResourceManager.GetString("CollectingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Durability 的本地化字符串。
        /// </summary>
        internal static string Durability {
            get {
                return ResourceManager.GetString("Durability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fishing 的本地化字符串。
        /// </summary>
        internal static string Fishing {
            get {
                return ResourceManager.GetString("Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gems and Orbs 的本地化字符串。
        /// </summary>
        internal static string GemsAndOrbs {
            get {
                return ResourceManager.GetString("GemsAndOrbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Groups 的本地化字符串。
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Health 的本地化字符串。
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inspecting 的本地化字符串。
        /// </summary>
        internal static string Inspecting {
            get {
                return ResourceManager.GetString("Inspecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mana 的本地化字符串。
        /// </summary>
        internal static string Mana {
            get {
                return ResourceManager.GetString("Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mounts 的本地化字符串。
        /// </summary>
        internal static string Mounts {
            get {
                return ResourceManager.GetString("Mounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Movements 的本地化字符串。
        /// </summary>
        internal static string Movements {
            get {
                return ResourceManager.GetString("Movements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchasing 的本地化字符串。
        /// </summary>
        internal static string Purchasing {
            get {
                return ResourceManager.GetString("Purchasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quests 的本地化字符串。
        /// </summary>
        internal static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repairing 的本地化字符串。
        /// </summary>
        internal static string Repairing {
            get {
                return ResourceManager.GetString("Repairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selling 的本地化字符串。
        /// </summary>
        internal static string Selling {
            get {
                return ResourceManager.GetString("Selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcut Information 的本地化字符串。
        /// </summary>
        internal static string ShortcutInformation {
            get {
                return ResourceManager.GetString("ShortcutInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skills 的本地化字符串。
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistics 的本地化字符串。
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trading 的本地化字符串。
        /// </summary>
        internal static string Trading {
            get {
                return ResourceManager.GetString("Trading", resourceCulture);
            }
        }
    }
}
