//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNPCDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNPCDialog() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceNPCDialog", typeof(ResourceNPCDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Accessory Items 的本地化字符串。
        /// </summary>
        internal static string AccessoryItems {
            get {
                return ResourceManager.GetString("AccessoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to bid {0:#,##0} Gold for {1}? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureYouWantToBidGoldFor {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToBidGoldFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to buy {0} for {1:#,##0} {2}? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureYouWantToBuyFor {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToBuyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auction has already ended for this item. 的本地化字符串。
        /// </summary>
        internal static string AuctionHasAlreadyEndedForThisItem {
            get {
                return ResourceManager.GetString("AuctionHasAlreadyEndedForThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. Auction cost is {0} gold, max starting bid is {1} gold per item \r\n\r\n2. 1% of final bid price is paid to Trust Merchant at auction end\r\n\r\n3. Maximum {2} days of item sale registration, afterwards the item will be sent to highest bidder\r\n\r\n4. Maximum of unlimited &quot;items allowed for auction\r\n\r\n 的本地化字符串。
        /// </summary>
        internal static string auctionText {
            get {
                return ResourceManager.GetString("auctionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awakening already at maximum level. 的本地化字符串。
        /// </summary>
        internal static string AwakeningAlreadyAtMaximumLevel {
            get {
                return ResourceManager.GetString("AwakeningAlreadyAtMaximumLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bid 的本地化字符串。
        /// </summary>
        internal static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bid Amount: 的本地化字符串。
        /// </summary>
        internal static string BidAmount {
            get {
                return ResourceManager.GetString("BidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bid Met 的本地化字符串。
        /// </summary>
        internal static string BidMet {
            get {
                return ResourceManager.GetString("BidMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body Glyph 的本地化字符串。
        /// </summary>
        internal static string BodyGlyph {
            get {
                return ResourceManager.GetString("BodyGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Books 的本地化字符串。
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bravery Glyp 的本地化字符串。
        /// </summary>
        internal static string BraveryGlyph {
            get {
                return ResourceManager.GetString("BraveryGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buff Pots 的本地化字符串。
        /// </summary>
        internal static string BuffPots {
            get {
                return ResourceManager.GetString("BuffPots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot awaken this item. 的本地化字符串。
        /// </summary>
        internal static string CannotAwakenThisItem {
            get {
                return ResourceManager.GetString("CannotAwakenThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot carry anymore gold. 的本地化字符串。
        /// </summary>
        internal static string CannotCarryAnymoreGold {
            get {
                return ResourceManager.GetString("CannotCarryAnymoreGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot consign this item. 的本地化字符串。
        /// </summary>
        internal static string CannotConsignThisItem {
            get {
                return ResourceManager.GetString("CannotConsignThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot repair this item. 的本地化字符串。
        /// </summary>
        internal static string CannotRepairThisItem {
            get {
                return ResourceManager.GetString("CannotRepairThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot sell this item. 的本地化字符串。
        /// </summary>
        internal static string CannotSellThisItem {
            get {
                return ResourceManager.GetString("CannotSellThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chance of Success 的本地化字符串。
        /// </summary>
        internal static string ChanceofSuccess {
            get {
                return ResourceManager.GetString("ChanceofSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Refine 的本地化字符串。
        /// </summary>
        internal static string CheckRefine {
            get {
                return ResourceManager.GetString("CheckRefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Complete) 的本地化字符串。
        /// </summary>
        internal static string CompleteBrackets {
            get {
                return ResourceManager.GetString("CompleteBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consignment 的本地化字符串。
        /// </summary>
        internal static string Consignment {
            get {
                return ResourceManager.GetString("Consignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consignment Price: 的本地化字符串。
        /// </summary>
        internal static string ConsignmentPrice {
            get {
                return ResourceManager.GetString("ConsignmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. Consignment is {0} gold per item \r\n\r\n2. 1% of sale price is paid to Trust Merchant at sale end\r\n\r\n3. Maximum {1} days of item sale registration until item is removed\r\n\r\n4. Maximum of unlimited items allowed for sale\r\n\r\n5. Sale price can be set between: {2} - {3} gold 的本地化字符串。
        /// </summary>
        internal static string consignmentText {
            get {
                return ResourceManager.GetString("consignmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consumable Items 的本地化字符串。
        /// </summary>
        internal static string ConsumableItems {
            get {
                return ResourceManager.GetString("ConsumableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Craft Amount: 的本地化字符串。
        /// </summary>
        internal static string CraftAmount {
            get {
                return ResourceManager.GetString("CraftAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Craft Items 的本地化字符串。
        /// </summary>
        internal static string CraftItems {
            get {
                return ResourceManager.GetString("CraftItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downgrade 的本地化字符串。
        /// </summary>
        internal static string Downgrade {
            get {
                return ResourceManager.GetString("Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drapery Items 的本地化字符串。
        /// </summary>
        internal static string DraperyItems {
            get {
                return ResourceManager.GetString("DraperyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 END DATE 的本地化字符串。
        /// </summary>
        internal static string ENDDATE {
            get {
                return ResourceManager.GetString("ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enhancement 的本地化字符串。
        /// </summary>
        internal static string Enhancement {
            get {
                return ResourceManager.GetString("Enhancement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EvilSlayer Glyph 的本地化字符串。
        /// </summary>
        internal static string EvilSlayerGlyph {
            get {
                return ResourceManager.GetString("EvilSlayerGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired 的本地化字符串。
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EXPIRY 的本地化字符串。
        /// </summary>
        internal static string EXPIRY {
            get {
                return ResourceManager.GetString("EXPIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Sale 的本地化字符串。
        /// </summary>
        internal static string ForSale {
            get {
                return ResourceManager.GetString("ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold 的本地化字符串。
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has not sold, Are you sure you want to get it back? 的本地化字符串。
        /// </summary>
        internal static string HasNotSoldAreYouSureYouWantToGetItBack {
            get {
                return ResourceManager.GetString("HasNotSoldAreYouSureYouWantToGetItBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HIGHEST BID 的本地化字符串。
        /// </summary>
        internal static string HIGHESTBID {
            get {
                return ResourceManager.GetString("HIGHESTBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I am interested in purchasing {0} for {1}. 的本地化字符串。
        /// </summary>
        internal static string IAmInterestedInPurchasingFor {
            get {
                return ResourceManager.GetString("IAmInterestedInPurchasingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (In Progress) 的本地化字符串。
        /// </summary>
        internal static string InProgressBrackets {
            get {
                return ResourceManager.GetString("InProgressBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} isn&apos;t a ring. 的本地化字符串。
        /// </summary>
        internal static string IsntARing {
            get {
                return ResourceManager.GetString("IsntARing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ITEM 的本地化字符串。
        /// </summary>
        internal static string ITEM {
            get {
                return ResourceManager.GetString("ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item will be Destroyed 的本地化字符串。
        /// </summary>
        internal static string ItemWillBeDestroyed {
            get {
                return ResourceManager.GetString("ItemWillBeDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magic Glyph 的本地化字符串。
        /// </summary>
        internal static string MagicGlyph {
            get {
                return ResourceManager.GetString("MagicGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Misc Items 的本地化字符串。
        /// </summary>
        internal static string MiscItems {
            get {
                return ResourceManager.GetString("MiscItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Bid 的本地化字符串。
        /// </summary>
        internal static string NoBid {
            get {
                return ResourceManager.GetString("NoBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough gold. 的本地化字符串。
        /// </summary>
        internal static string NotEnoughGold {
            get {
                return ResourceManager.GetString("NotEnoughGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orbs 的本地化字符串。
        /// </summary>
        internal static string Orbs {
            get {
                return ResourceManager.GetString("Orbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRICE 的本地化字符串。
        /// </summary>
        internal static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PRICE / BID 的本地化字符串。
        /// </summary>
        internal static string PRICEBID {
            get {
                return ResourceManager.GetString("PRICEBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price: {0} gold 的本地化字符串。
        /// </summary>
        internal static string PriceGold {
            get {
                return ResourceManager.GetString("PriceGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price: {0} pearls 的本地化字符串。
        /// </summary>
        internal static string PricePearl {
            get {
                return ResourceManager.GetString("PricePearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protection Glyph 的本地化字符串。
        /// </summary>
        internal static string ProtectionGlyph {
            get {
                return ResourceManager.GetString("ProtectionGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchase Amount: 的本地化字符串。
        /// </summary>
        internal static string PurchaseAmount {
            get {
                return ResourceManager.GetString("PurchaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quantity 的本地化字符串。
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recovery Pots 的本地化字符串。
        /// </summary>
        internal static string RecoveryPots {
            get {
                return ResourceManager.GetString("RecoveryPots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refine 的本地化字符串。
        /// </summary>
        internal static string Refine {
            get {
                return ResourceManager.GetString("Refine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repair 的本地化字符串。
        /// </summary>
        internal static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sale 的本地化字符串。
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SALE PRICE 的本地化字符串。
        /// </summary>
        internal static string SALEPRICE {
            get {
                return ResourceManager.GetString("SALEPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scrolls / Oils 的本地化字符串。
        /// </summary>
        internal static string ScrollsOils {
            get {
                return ResourceManager.GetString("ScrollsOils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Upgrade Item. 的本地化字符串。
        /// </summary>
        internal static string SelectUpgradeItem {
            get {
                return ResourceManager.GetString("SelectUpgradeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Upgrade Type. 的本地化字符串。
        /// </summary>
        internal static string SelectUpgradeType {
            get {
                return ResourceManager.GetString("SelectUpgradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELLER / EXPIRY 的本地化字符串。
        /// </summary>
        internal static string SELLEREXPIRY {
            get {
                return ResourceManager.GetString("SELLEREXPIRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELL ITEM 的本地化字符串。
        /// </summary>
        internal static string SELLITEM {
            get {
                return ResourceManager.GetString("SELLITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show All Items 的本地化字符串。
        /// </summary>
        internal static string ShowAllItems {
            get {
                return ResourceManager.GetString("ShowAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sold 的本地化字符串。
        /// </summary>
        internal static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soul Glyph 的本地化字符串。
        /// </summary>
        internal static string SoulGlyph {
            get {
                return ResourceManager.GetString("SoulGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S. Repair 的本地化字符串。
        /// </summary>
        internal static string SpecialRepair {
            get {
                return ResourceManager.GetString("SpecialRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STARTING BID 的本地化字符串。
        /// </summary>
        internal static string STARTINGBID {
            get {
                return ResourceManager.GetString("STARTINGBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tasks 的本地化字符串。
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item has already been sold. 的本地化字符串。
        /// </summary>
        internal static string ThisItemHasAlreadyBeenSold {
            get {
                return ResourceManager.GetString("ThisItemHasAlreadyBeenSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item has Expired and cannot be bought. 的本地化字符串。
        /// </summary>
        internal static string ThisItemHasExpiredAndCannotBeBrought {
            get {
                return ResourceManager.GetString("ThisItemHasExpiredAndCannotBeBrought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This item has not met the minimum bid yet. 的本地化字符串。
        /// </summary>
        internal static string ThisItemHasNotMetTheMinimumBidYet {
            get {
                return ResourceManager.GetString("ThisItemHasNotMetTheMinimumBidYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon Items 的本地化字符串。
        /// </summary>
        internal static string WeaponItems {
            get {
                return ResourceManager.GetString("WeaponItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are too far away from the Trust Merchant. 的本地化字符串。
        /// </summary>
        internal static string YouAreTooFarAwayFromTheTrustMerchant {
            get {
                return ResourceManager.GetString("YouAreTooFarAwayFromTheTrustMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot buy from the TrustMerchant without using. 的本地化字符串。
        /// </summary>
        internal static string YouCannotBuyFromTheTrustMerchantWithoutUsing {
            get {
                return ResourceManager.GetString("YouCannotBuyFromTheTrustMerchantWithoutUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot buy your own items. 的本地化字符串。
        /// </summary>
        internal static string YouCannotBuyYourOwnItems {
            get {
                return ResourceManager.GetString("YouCannotBuyYourOwnItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot hold enough gold to get your sale. 的本地化字符串。
        /// </summary>
        internal static string YouCannotHoldEnoughGoldToGetYourSale {
            get {
                return ResourceManager.GetString("YouCannotHoldEnoughGoldToGetYourSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot purchase any more items. 的本地化字符串。
        /// </summary>
        internal static string YouCannotPpurchaseAnymoreItems {
            get {
                return ResourceManager.GetString("YouCannotPpurchaseAnymoreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot use the TrustMerchant when dead. 的本地化字符串。
        /// </summary>
        internal static string YouCannotUseTheTrustMerchantWhenDead {
            get {
                return ResourceManager.GetString("YouCannotUseTheTrustMerchantWhenDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can search again after {0} seconds. 的本地化字符串。
        /// </summary>
        internal static string YouCanSearchAgainAfterSeconds {
            get {
                return ResourceManager.GetString("YouCanSearchAgainAfterSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have the required tools or ingredients. 的本地化字符串。
        /// </summary>
        internal static string YouDoDotHaveTheRequiredToolsOrIngredients {
            get {
                return ResourceManager.GetString("YouDoDotHaveTheRequiredToolsOrIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough gold. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveEnoughGold {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough Pearls. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveEnoughPearls {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughPearls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough weight. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveEnoughWeight {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough weight or space spare to buy this item. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveEnoughWeightOrSpaceSpareToBuyThisItem {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughWeightOrSpaceSpareToBuyThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have enough gold to refine your {0}. 的本地化字符串。
        /// </summary>
        internal static string YouDontHaveEnoughGoldToRefineYour {
            get {
                return ResourceManager.GetString("YouDontHaveEnoughGoldToRefineYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have not supplied enough materials. 的本地化字符串。
        /// </summary>
        internal static string YouHaveNotSuppliedEnoughMaterials {
            get {
                return ResourceManager.GetString("YouHaveNotSuppliedEnoughMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t deposited any items to refine your {0} with. 的本地化字符串。
        /// </summary>
        internal static string YouHaventDepositedAnyItemsToRefineYourWith {
            get {
                return ResourceManager.GetString("YouHaventDepositedAnyItemsToRefineYourWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your {0} hasn&apos;t been refined so it doesn&apos;t need checking. 的本地化字符串。
        /// </summary>
        internal static string YourHasntBeenRefinedSoItDoesntNeedChecking {
            get {
                return ResourceManager.GetString("YourHasntBeenRefinedSoItDoesntNeedChecking", resourceCulture);
            }
        }
    }
}
