//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceNPCDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNPCDialog() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceNPCDialog", typeof(ResourceNPCDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Body Glyph 的本地化字符串。
        /// </summary>
        internal static string BodyGlyph {
            get {
                return ResourceManager.GetString("BodyGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bravery Glyp 的本地化字符串。
        /// </summary>
        internal static string BraveryGlyph {
            get {
                return ResourceManager.GetString("BraveryGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot carry anymore gold. 的本地化字符串。
        /// </summary>
        internal static string CannotCarryAnymoreGold {
            get {
                return ResourceManager.GetString("CannotCarryAnymoreGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot consign this item. 的本地化字符串。
        /// </summary>
        internal static string CannotConsignThisItem {
            get {
                return ResourceManager.GetString("CannotConsignThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot repair this item. 的本地化字符串。
        /// </summary>
        internal static string CannotRepairThisItem {
            get {
                return ResourceManager.GetString("CannotRepairThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot sell this item. 的本地化字符串。
        /// </summary>
        internal static string CannotSellThisItem {
            get {
                return ResourceManager.GetString("CannotSellThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chance of Success 的本地化字符串。
        /// </summary>
        internal static string ChanceofSuccess {
            get {
                return ResourceManager.GetString("ChanceofSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Refine 的本地化字符串。
        /// </summary>
        internal static string CheckRefine {
            get {
                return ResourceManager.GetString("CheckRefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consignment 的本地化字符串。
        /// </summary>
        internal static string Consignment {
            get {
                return ResourceManager.GetString("Consignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Consignment Price: 的本地化字符串。
        /// </summary>
        internal static string ConsignmentPrice {
            get {
                return ResourceManager.GetString("ConsignmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Craft Amount: 的本地化字符串。
        /// </summary>
        internal static string CraftAmount {
            get {
                return ResourceManager.GetString("CraftAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downgrade 的本地化字符串。
        /// </summary>
        internal static string Downgrade {
            get {
                return ResourceManager.GetString("Downgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EvilSlayer Glyph 的本地化字符串。
        /// </summary>
        internal static string EvilSlayerGlyph {
            get {
                return ResourceManager.GetString("EvilSlayerGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold 的本地化字符串。
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} isn&apos;t a ring. 的本地化字符串。
        /// </summary>
        internal static string IsntARing {
            get {
                return ResourceManager.GetString("IsntARing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item will be Destroyed 的本地化字符串。
        /// </summary>
        internal static string ItemWillBeDestroyed {
            get {
                return ResourceManager.GetString("ItemWillBeDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magic Glyph 的本地化字符串。
        /// </summary>
        internal static string MagicGlyph {
            get {
                return ResourceManager.GetString("MagicGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price: {0} gold 的本地化字符串。
        /// </summary>
        internal static string PriceGold {
            get {
                return ResourceManager.GetString("PriceGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price: {0} pearls 的本地化字符串。
        /// </summary>
        internal static string PricePearl {
            get {
                return ResourceManager.GetString("PricePearl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protection Glyph 的本地化字符串。
        /// </summary>
        internal static string ProtectionGlyph {
            get {
                return ResourceManager.GetString("ProtectionGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchase Amount: 的本地化字符串。
        /// </summary>
        internal static string PurchaseAmount {
            get {
                return ResourceManager.GetString("PurchaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quantity 的本地化字符串。
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refine 的本地化字符串。
        /// </summary>
        internal static string Refine {
            get {
                return ResourceManager.GetString("Refine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repair 的本地化字符串。
        /// </summary>
        internal static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        internal static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sale 的本地化字符串。
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Upgrade Item. 的本地化字符串。
        /// </summary>
        internal static string SelectUpgradeItem {
            get {
                return ResourceManager.GetString("SelectUpgradeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Upgrade Type. 的本地化字符串。
        /// </summary>
        internal static string SelectUpgradeType {
            get {
                return ResourceManager.GetString("SelectUpgradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soul Glyph 的本地化字符串。
        /// </summary>
        internal static string SoulGlyph {
            get {
                return ResourceManager.GetString("SoulGlyph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S. Repair 的本地化字符串。
        /// </summary>
        internal static string SpecialRepair {
            get {
                return ResourceManager.GetString("SpecialRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot purchase any more items. 的本地化字符串。
        /// </summary>
        internal static string YouCannotPpurchaseAnymoreItems {
            get {
                return ResourceManager.GetString("YouCannotPpurchaseAnymoreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have the required tools or ingredients. 的本地化字符串。
        /// </summary>
        internal static string YouDoDotHaveTheRequiredToolsOrIngredients {
            get {
                return ResourceManager.GetString("YouDoDotHaveTheRequiredToolsOrIngredients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough gold. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveEnoughGold {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough Pearls. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveEnoughPearls {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughPearls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You do not have enough weight. 的本地化字符串。
        /// </summary>
        internal static string YouDoNotHaveEnoughWeight {
            get {
                return ResourceManager.GetString("YouDoNotHaveEnoughWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have enough gold to refine your {0}. 的本地化字符串。
        /// </summary>
        internal static string YouDontHaveEnoughGoldToRefineYour {
            get {
                return ResourceManager.GetString("YouDontHaveEnoughGoldToRefineYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You haven&apos;t deposited any items to refine your {0} with. 的本地化字符串。
        /// </summary>
        internal static string YouHaventDepositedAnyItemsToRefineYourWith {
            get {
                return ResourceManager.GetString("YouHaventDepositedAnyItemsToRefineYourWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your {0} hasn&apos;t been refined so it doesn&apos;t need checking. 的本地化字符串。
        /// </summary>
        internal static string YourHasntBeenRefinedSoItDoesntNeedChecking {
            get {
                return ResourceManager.GetString("YourHasntBeenRefinedSoItDoesntNeedChecking", resourceCulture);
            }
        }
    }
}
