//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceGuild {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGuild() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceGuild", typeof(ResourceGuild).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Activate Buff 的本地化字符串。
        /// </summary>
        internal static string ActivateBuff {
            get {
                return ResourceManager.GetString("ActivateBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activation Cost: 的本地化字符串。
        /// </summary>
        internal static string ActivationCost {
            get {
                return ResourceManager.GetString("ActivationCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add New 的本地化字符串。
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alter alliance 的本地化字符串。
        /// </summary>
        internal static string AlterAlliance {
            get {
                return ResourceManager.GetString("AlterAlliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to change the rank of {0} to {1}? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureYouWantToChangeTheRankOfTo {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToChangeTheRankOfTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to create a new rank? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureYouWantToCreateANewRank {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToCreateANewRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to kick {0}? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureYouWantToKick {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available 的本地化字符串。
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buff is still active. 的本地化字符串。
        /// </summary>
        internal static string BuffIsStillActive {
            get {
                return ResourceManager.GetString("BuffIsStillActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Buff Length: {0} minutes. 的本地化字符串。
        /// </summary>
        internal static string BuffLengthMinutes {
            get {
                return ResourceManager.GetString("BuffLengthMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change notice 的本地化字符串。
        /// </summary>
        internal static string ChangeNotice {
            get {
                return ResourceManager.GetString("ChangeNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Counting down. 的本地化字符串。
        /// </summary>
        internal static string CountingDown {
            get {
                return ResourceManager.GetString("CountingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Days ago 的本地化字符串。
        /// </summary>
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decreases 的本地化字符串。
        /// </summary>
        internal static string Decreases {
            get {
                return ResourceManager.GetString("Decreases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposit 的本地化字符串。
        /// </summary>
        internal static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Rank 的本地化字符串。
        /// </summary>
        internal static string EditRank {
            get {
                return ResourceManager.GetString("EditRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit ranks 的本地化字符串。
        /// </summary>
        internal static string EditRanks {
            get {
                return ResourceManager.GetString("EditRanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired. 的本地化字符串。
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 gold 的本地化字符串。
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold to retrieve: 的本地化字符串。
        /// </summary>
        internal static string GoldToRetrieve {
            get {
                return ResourceManager.GetString("GoldToRetrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guild level too low. 的本地化字符串。
        /// </summary>
        internal static string GuildLevelTooLow {
            get {
                return ResourceManager.GetString("GuildLevelTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guild Name{0}{0}Level{0}{0}Members 的本地化字符串。
        /// </summary>
        internal static string GuildNameLevelMembers {
            get {
                return ResourceManager.GetString("GuildNameLevelMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guild rank does not allow buff activation. 的本地化字符串。
        /// </summary>
        internal static string GuildRankDoesNotAllowBuffActivation {
            get {
                return ResourceManager.GetString("GuildRankDoesNotAllowBuffActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inactive 的本地化字符串。
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increases 的本地化字符串。
        /// </summary>
        internal static string Increases {
            get {
                return ResourceManager.GetString("Increases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient guild funds. 的本地化字符串。
        /// </summary>
        internal static string InsufficientGuildFunds {
            get {
                return ResourceManager.GetString("InsufficientGuildFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient Level 的本地化字符串。
        /// </summary>
        internal static string InsufficientLevel {
            get {
                return ResourceManager.GetString("InsufficientLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient points available. 的本地化字符串。
        /// </summary>
        internal static string InsufficientPointsAvailable {
            get {
                return ResourceManager.GetString("InsufficientPointsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kick member 的本地化字符串。
        /// </summary>
        internal static string KickMember {
            get {
                return ResourceManager.GetString("KickMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum Guild Level:  的本地化字符串。
        /// </summary>
        internal static string MinimumGuildLevel {
            get {
                return ResourceManager.GetString("MinimumGuildLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing Rank 的本地化字符串。
        /// </summary>
        internal static string MissingRank {
            get {
                return ResourceManager.GetString("MissingRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obtained. 的本地化字符串。
        /// </summary>
        internal static string Obtained {
            get {
                return ResourceManager.GetString("Obtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online 的本地化字符串。
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Points Required:  的本地化字符串。
        /// </summary>
        internal static string PointsRequired {
            get {
                return ResourceManager.GetString("PointsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rank-{0} 的本地化字符串。
        /// </summary>
        internal static string RankName {
            get {
                return ResourceManager.GetString("RankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recruit member 的本地化字符串。
        /// </summary>
        internal static string RecruitMember {
            get {
                return ResourceManager.GetString("RecruitMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieve item 的本地化字符串。
        /// </summary>
        internal static string RetrieveItem {
            get {
                return ResourceManager.GetString("RetrieveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Rank 的本地化字符串。
        /// </summary>
        internal static string SelectRank {
            get {
                return ResourceManager.GetString("SelectRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Offline 的本地化字符串。
        /// </summary>
        internal static string ShowOffline {
            get {
                return ResourceManager.GetString("ShowOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store item 的本地化字符串。
        /// </summary>
        internal static string StoreItem {
            get {
                return ResourceManager.GetString("StoreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Remaining: {0} minutes 的本地化字符串。
        /// </summary>
        internal static string TimeRemainingMinutes {
            get {
                return ResourceManager.GetString("TimeRemainingMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yesterday 的本地化字符串。
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
