//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceItemInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceItemInfo() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceItemInfo", typeof(ResourceItemInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Adds 的本地化字符串。
        /// </summary>
        internal static string Adds {
            get {
                return ResourceManager.GetString("Adds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BagWeight 的本地化字符串。
        /// </summary>
        internal static string BagWeight {
            get {
                return ResourceManager.GetString("BagWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t drop 的本地化字符串。
        /// </summary>
        internal static string CantDrop {
            get {
                return ResourceManager.GetString("CantDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t drop on death 的本地化字符串。
        /// </summary>
        internal static string CantDropOnDeath {
            get {
                return ResourceManager.GetString("CantDropOnDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t trade 的本地化字符串。
        /// </summary>
        internal static string CantTrade {
            get {
                return ResourceManager.GetString("CantTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destroyed when dropped 的本地化字符串。
        /// </summary>
        internal static string DestroyedWhenDropped {
            get {
                return ResourceManager.GetString("DestroyedWhenDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop 的本地化字符串。
        /// </summary>
        internal static string Drop {
            get {
                return ResourceManager.GetString("Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Durability 的本地化字符串。
        /// </summary>
        internal static string Durability {
            get {
                return ResourceManager.GetString("Durability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp 的本地化字符串。
        /// </summary>
        internal static string Exp {
            get {
                return ResourceManager.GetString("Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Health Recovery 的本地化字符串。
        /// </summary>
        internal static string HealthRecovery {
            get {
                return ResourceManager.GetString("HealthRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loyalty 的本地化字符串。
        /// </summary>
        internal static string Loyalty {
            get {
                return ResourceManager.GetString("Loyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max HP 的本地化字符串。
        /// </summary>
        internal static string MaxHP {
            get {
                return ResourceManager.GetString("MaxHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max MP 的本地化字符串。
        /// </summary>
        internal static string MaxMP {
            get {
                return ResourceManager.GetString("MaxMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nutrition 的本地化字符串。
        /// </summary>
        internal static string Nutrition {
            get {
                return ResourceManager.GetString("Nutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purity 的本地化字符串。
        /// </summary>
        internal static string Purity {
            get {
                return ResourceManager.GetString("Purity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 的本地化字符串。
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage 的本地化字符串。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
