//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceRankDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRankDialog() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceRankDialog", typeof(ResourceRankDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Not Listed 的本地化字符串。
        /// </summary>
        internal static string NotListed {
            get {
                return ResourceManager.GetString("NotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overall TOP 20 的本地化字符串。
        /// </summary>
        internal static string OverallTOP20 {
            get {
                return ResourceManager.GetString("OverallTOP20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranked 的本地化字符串。
        /// </summary>
        internal static string Ranked {
            get {
                return ResourceManager.GetString("Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOP 20 Archers 的本地化字符串。
        /// </summary>
        internal static string TOP20Archers {
            get {
                return ResourceManager.GetString("TOP20Archers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOP 20 Assasins 的本地化字符串。
        /// </summary>
        internal static string TOP20Assasins {
            get {
                return ResourceManager.GetString("TOP20Assasins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOP 20 Taoists 的本地化字符串。
        /// </summary>
        internal static string TOP20Taoists {
            get {
                return ResourceManager.GetString("TOP20Taoists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOP 20 Warriors 的本地化字符串。
        /// </summary>
        internal static string TOP20Warriors {
            get {
                return ResourceManager.GetString("TOP20Warriors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TOP 20 Wizards 的本地化字符串。
        /// </summary>
        internal static string TOP20Wizards {
            get {
                return ResourceManager.GetString("TOP20Wizards", resourceCulture);
            }
        }
    }
}
