//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceShortcuts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceShortcuts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceShortcuts", typeof(ResourceShortcuts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All Attack Mode - Attack all subjects 的本地化字符串。
        /// </summary>
        internal static string AllAttackModeAttackAllSubjects {
            get {
                return ResourceManager.GetString("AllAttackModeAttackAllSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto run on / off 的本地化字符串。
        /// </summary>
        internal static string AutoRunOnOff {
            get {
                return ResourceManager.GetString("AutoRunOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Belt window (open / close) 的本地化字符串。
        /// </summary>
        internal static string BeltWindowOpenClose {
            get {
                return ResourceManager.GetString("BeltWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command to guild chat 的本地化字符串。
        /// </summary>
        internal static string CommandToGuildChat {
            get {
                return ResourceManager.GetString("CommandToGuildChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command to shout to others nearby 的本地化字符串。
        /// </summary>
        internal static string CommandToShoutToOthersNearby {
            get {
                return ResourceManager.GetString("CommandToShoutToOthersNearby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command to whisper to others 的本地化字符串。
        /// </summary>
        internal static string CommandToWhisperToOthers {
            get {
                return ResourceManager.GetString("CommandToWhisperToOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creature Pickup (Multi Mouse Target) 的本地化字符串。
        /// </summary>
        internal static string CreaturePickupMultiMouseTarget {
            get {
                return ResourceManager.GetString("CreaturePickupMultiMouseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creature Pickup (Single Mouse Target) 的本地化字符串。
        /// </summary>
        internal static string CreaturePickupSingleMouseTarget {
            get {
                return ResourceManager.GetString("CreaturePickupSingleMouseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Engagement window (open / close) 的本地化字符串。
        /// </summary>
        internal static string EngagementWindowOpenClose {
            get {
                return ResourceManager.GetString("EngagementWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit the game 的本地化字符串。
        /// </summary>
        internal static string ExitTheGame {
            get {
                return ResourceManager.GetString("ExitTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fishing window (open / close) 的本地化字符串。
        /// </summary>
        internal static string FishingWindowOpenClose {
            get {
                return ResourceManager.GetString("FishingWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friend window (open / close) 的本地化字符串。
        /// </summary>
        internal static string FriendWindowOpenClose {
            get {
                return ResourceManager.GetString("FriendWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gameshop window (open / close) 的本地化字符串。
        /// </summary>
        internal static string GameshopWindowOpenClose {
            get {
                return ResourceManager.GetString("GameshopWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Good/Evil Mode - Attack PK players and monsters only 的本地化字符串。
        /// </summary>
        internal static string GoodEvilModeAttackPKPlayersAndMonstersOnly {
            get {
                return ResourceManager.GetString("GoodEvilModeAttackPKPlayersAndMonstersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Mode - Attack all subjects except your group members 的本地化字符串。
        /// </summary>
        internal static string GroupModeAttackAllSubjectsExceptYourGroupMembers {
            get {
                return ResourceManager.GetString("GroupModeAttackAllSubjectsExceptYourGroupMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group window (open / close) 的本地化字符串。
        /// </summary>
        internal static string GroupWindowOpenClose {
            get {
                return ResourceManager.GetString("GroupWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guild Mode - Attack all subjects except your guild members 的本地化字符串。
        /// </summary>
        internal static string GuildModeAttackAllSubjectsExceptYourGuildMembers {
            get {
                return ResourceManager.GetString("GuildModeAttackAllSubjectsExceptYourGuildMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guild window (open / close) 的本地化字符串。
        /// </summary>
        internal static string GuildWindowOpenClose {
            get {
                return ResourceManager.GetString("GuildWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help window (open / close) 的本地化字符串。
        /// </summary>
        internal static string HelpWindowOpenClose {
            get {
                return ResourceManager.GetString("HelpWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight / Pickup Items 的本地化字符串。
        /// </summary>
        internal static string HighlightPickupItems {
            get {
                return ResourceManager.GetString("HighlightPickupItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory window (open / close) 的本地化字符串。
        /// </summary>
        internal static string InventoryWindowOpenClose {
            get {
                return ResourceManager.GetString("InventoryWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log out 的本地化字符串。
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mentor window (open / close) 的本地化字符串。
        /// </summary>
        internal static string MentorWindowOpenClose {
            get {
                return ResourceManager.GetString("MentorWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimap window (open / close) 的本地化字符串。
        /// </summary>
        internal static string MinimapWindowOpenClose {
            get {
                return ResourceManager.GetString("MinimapWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mount / Dismount ride 的本地化字符串。
        /// </summary>
        internal static string MountDismounRide {
            get {
                return ResourceManager.GetString("MountDismounRide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option window (open / close) 的本地化字符串。
        /// </summary>
        internal static string OptionWindowOpenClose {
            get {
                return ResourceManager.GetString("OptionWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peace Mode - Attack monsters only 的本地化字符串。
        /// </summary>
        internal static string PeaceModeAttackMonstersOnly {
            get {
                return ResourceManager.GetString("PeaceModeAttackMonstersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right Click 的本地化字符串。
        /// </summary>
        internal static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen Capture 的本地化字符串。
        /// </summary>
        internal static string ScreenCapture {
            get {
                return ResourceManager.GetString("ScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shortcuts 的本地化字符串。
        /// </summary>
        internal static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show / Hide interface 的本地化字符串。
        /// </summary>
        internal static string ShowHideInterface {
            get {
                return ResourceManager.GetString("ShowHideInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show other players kits 的本地化字符串。
        /// </summary>
        internal static string ShowOtherPlayersKits {
            get {
                return ResourceManager.GetString("ShowOtherPlayersKits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show the field map 的本地化字符串。
        /// </summary>
        internal static string ShowTheFieldMap {
            get {
                return ResourceManager.GetString("ShowTheFieldMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show the skill bar 的本地化字符串。
        /// </summary>
        internal static string ShowTheSkillBar {
            get {
                return ResourceManager.GetString("ShowTheSkillBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill buttons 的本地化字符串。
        /// </summary>
        internal static string SkillButtons {
            get {
                return ResourceManager.GetString("SkillButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skill window (open / close) 的本地化字符串。
        /// </summary>
        internal static string SkillWindowOpenClose {
            get {
                return ResourceManager.GetString("SkillWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status window (open / close) 的本地化字符串。
        /// </summary>
        internal static string StatusWindowOpenClose {
            get {
                return ResourceManager.GetString("StatusWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 text 的本地化字符串。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle pet attack mode 的本地化字符串。
        /// </summary>
        internal static string TogglePetAttackMode {
            get {
                return ResourceManager.GetString("TogglePetAttackMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle player attack mode 的本地化字符串。
        /// </summary>
        internal static string TogglePlayerAttackMode {
            get {
                return ResourceManager.GetString("TogglePlayerAttackMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trade window (open / close) 的本地化字符串。
        /// </summary>
        internal static string TradeWindowOpenClose {
            get {
                return ResourceManager.GetString("TradeWindowOpenClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 username 的本地化字符串。
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
