//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCharStat2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCharStat2() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceCharStat2", typeof(ResourceCharStat2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Armour Weight 的本地化字符串。
        /// </summary>
        internal static string ArmourWeight {
            get {
                return ResourceManager.GetString("ArmourWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bag Weight 的本地化字符串。
        /// </summary>
        internal static string BagWeight {
            get {
                return ResourceManager.GetString("BagWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experience 的本地化字符串。
        /// </summary>
        internal static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frost Power 的本地化字符串。
        /// </summary>
        internal static string FrostPower {
            get {
                return ResourceManager.GetString("FrostPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hand Weight 的本地化字符串。
        /// </summary>
        internal static string HandWeight {
            get {
                return ResourceManager.GetString("HandWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Health Recovery 的本地化字符串。
        /// </summary>
        internal static string HealthRecovery {
            get {
                return ResourceManager.GetString("HealthRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Holy Power 的本地化字符串。
        /// </summary>
        internal static string HolyPower {
            get {
                return ResourceManager.GetString("HolyPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Magic Resistance 的本地化字符串。
        /// </summary>
        internal static string MagicResistance {
            get {
                return ResourceManager.GetString("MagicResistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mana Recovery 的本地化字符串。
        /// </summary>
        internal static string ManaRecovery {
            get {
                return ResourceManager.GetString("ManaRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Poison Power 的本地化字符串。
        /// </summary>
        internal static string PoisonPower {
            get {
                return ResourceManager.GetString("PoisonPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Poison Recovery 的本地化字符串。
        /// </summary>
        internal static string PoisonRecovery {
            get {
                return ResourceManager.GetString("PoisonRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Poison Resistance 的本地化字符串。
        /// </summary>
        internal static string PoisonResistance {
            get {
                return ResourceManager.GetString("PoisonResistance", resourceCulture);
            }
        }
    }
}
