//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCommon() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceCommon", typeof(ResourceCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All Items 的本地化字符串。
        /// </summary>
        internal static string AllItems {
            get {
                return ResourceManager.GetString("AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow/Block Recall 的本地化字符串。
        /// </summary>
        internal static string AllowBlockRecall {
            get {
                return ResourceManager.GetString("AllowBlockRecall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected: Another user logged onto your account. 的本地化字符串。
        /// </summary>
        internal static string AnotherUserLoggedOntoYourAccount {
            get {
                return ResourceManager.GetString("AnotherUserLoggedOntoYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Archer 的本地化字符串。
        /// </summary>
        internal static string Archer {
            get {
                return ResourceManager.GetString("Archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to cancel this quest? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureYouWantToCancelThisQuest {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToCancelThisQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you wish to remove &apos;{0}&apos;? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureYouWishToRemove {
            get {
                return ResourceManager.GetString("AreYouSureYouWishToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assassin 的本地化字符串。
        /// </summary>
        internal static string Assassin {
            get {
                return ResourceManager.GetString("Assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancelling a Mentorship early will cause a cooldown. Are you sure? 的本地化字符串。
        /// </summary>
        internal static string CancellingAMentorshipEarlyWillCauseACooldownAreYouSure {
            get {
                return ResourceManager.GetString("CancellingAMentorshipEarlyWillCauseACooldownAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Credits 的本地化字符串。
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crit 的本地化字符串。
        /// </summary>
        internal static string Crit {
            get {
                return ResourceManager.GetString("Crit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Days 的本地化字符串。
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deal cancelled.{0}To deal correctly you must face the other party. 的本地化字符串。
        /// </summary>
        internal static string DealCancelledToDealCorrectlyYouMustFaceTheOtherParty {
            get {
                return ResourceManager.GetString("DealCancelledToDealCorrectlyYouMustFaceTheOtherParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Divorced Date 的本地化字符串。
        /// </summary>
        internal static string DivorcedDate {
            get {
                return ResourceManager.GetString("DivorcedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use Cross Half Moon. 的本地化字符串。
        /// </summary>
        internal static string DoNotUseCrossHalfMoon {
            get {
                return ResourceManager.GetString("DoNotUseCrossHalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use Double Slash. 的本地化字符串。
        /// </summary>
        internal static string DoNotUseDoubleSlash {
            get {
                return ResourceManager.GetString("DoNotUseDoubleSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use Half Moon. 的本地化字符串。
        /// </summary>
        internal static string DoNotUseHalfMoon {
            get {
                return ResourceManager.GetString("DoNotUseHalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not use Thrusting. 的本地化字符串。
        /// </summary>
        internal static string DoNotUseThrusting {
            get {
                return ResourceManager.GetString("DoNotUseThrusting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold 的本地化字符串。
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} got removed from the guild. 的本地化字符串。
        /// </summary>
        internal static string GotRemovedFromTheGuild {
            get {
                return ResourceManager.GetString("GotRemovedFromTheGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} joined guild. 的本地化字符串。
        /// </summary>
        internal static string JoinedGuild {
            get {
                return ResourceManager.GetString("JoinedGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected: Kicked by Admin. 的本地化字符串。
        /// </summary>
        internal static string KickedByAdmin {
            get {
                return ResourceManager.GetString("KickedByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Online 的本地化字符串。
        /// </summary>
        internal static string LastOnline {
            get {
                return ResourceManager.GetString("LastOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} left the guild. 的本地化字符串。
        /// </summary>
        internal static string LeftTheGuild {
            get {
                return ResourceManager.GetString("LeftTheGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location 的本地化字符串。
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location:  Offline 的本地化字符串。
        /// </summary>
        internal static string LocationOffline {
            get {
                return ResourceManager.GetString("LocationOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} logged on. 的本地化字符串。
        /// </summary>
        internal static string LoggedOn {
            get {
                return ResourceManager.GetString("LoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lover 的本地化字符串。
        /// </summary>
        internal static string Lover {
            get {
                return ResourceManager.GetString("Lover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lover is not online 的本地化字符串。
        /// </summary>
        internal static string LoverIsNotOnline {
            get {
                return ResourceManager.GetString("LoverIsNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lv 的本地化字符串。
        /// </summary>
        internal static string Lv {
            get {
                return ResourceManager.GetString("Lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marriage Date 的本地化字符串。
        /// </summary>
        internal static string MarriageDate {
            get {
                return ResourceManager.GetString("MarriageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Marriage Length 的本地化字符串。
        /// </summary>
        internal static string MarriageLength {
            get {
                return ResourceManager.GetString("MarriageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected: Maximum connections reached. 的本地化字符串。
        /// </summary>
        internal static string MaximumConnectionsReached {
            get {
                return ResourceManager.GetString("MaximumConnectionsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MENTEE 的本地化字符串。
        /// </summary>
        internal static string MENTEE {
            get {
                return ResourceManager.GetString("MENTEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MENTEE EXP 的本地化字符串。
        /// </summary>
        internal static string MENTEEEXP {
            get {
                return ResourceManager.GetString("MENTEEEXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MENTOR 的本地化字符串。
        /// </summary>
        internal static string MENTOR {
            get {
                return ResourceManager.GetString("MENTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miss 的本地化字符串。
        /// </summary>
        internal static string Miss {
            get {
                return ResourceManager.GetString("Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monster {0} x{1} has been spawned. 的本地化字符串。
        /// </summary>
        internal static string MonsterHasBeenSpawned {
            get {
                return ResourceManager.GetString("MonsterHasBeenSpawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Needed 的本地化字符串。
        /// </summary>
        internal static string Needed {
            get {
                return ResourceManager.GetString("Needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never 的本地化字符串。
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ONLINE 的本地化字符串。
        /// </summary>
        internal static string ONLINE {
            get {
                return ResourceManager.GetString("ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected: Packet Error. 的本地化字符串。
        /// </summary>
        internal static string PacketError {
            get {
                return ResourceManager.GetString("PacketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player is not online 的本地化字符串。
        /// </summary>
        internal static string PlayerIsNotOnline {
            get {
                return ResourceManager.GetString("PlayerIsNotOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please give your creature a name. 的本地化字符串。
        /// </summary>
        internal static string PleaseGiveYourCreatureAName {
            get {
                return ResourceManager.GetString("PleaseGiveYourCreatureAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait, The game is still loading... {0:##0}% 的本地化字符串。
        /// </summary>
        internal static string PleaseWaitTheGameIsStillLoading {
            get {
                return ResourceManager.GetString("PleaseWaitTheGameIsStillLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected: Server Crashed. 的本地化字符串。
        /// </summary>
        internal static string ServerCrashed {
            get {
                return ResourceManager.GetString("ServerCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Legend of Mir 2 的本地化字符串。
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected: Server is shutting down. 的本地化字符串。
        /// </summary>
        internal static string ShuttingDown {
            get {
                return ResourceManager.GetString("ShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taoist 的本地化字符串。
        /// </summary>
        internal static string Taoist {
            get {
                return ResourceManager.GetString("Taoist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target is too far. 的本地化字符串。
        /// </summary>
        internal static string TargetIsTooFar {
            get {
                return ResourceManager.GetString("TargetIsTooFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Since 的本地化字符串。
        /// </summary>
        internal static string TimeSince {
            get {
                return ResourceManager.GetString("TimeSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Cross Half Moon. 的本地化字符串。
        /// </summary>
        internal static string UseCrossHalfMoon {
            get {
                return ResourceManager.GetString("UseCrossHalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Double Slash. 的本地化字符串。
        /// </summary>
        internal static string UseDoubleSlash {
            get {
                return ResourceManager.GetString("UseDoubleSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Half Moon. 的本地化字符串。
        /// </summary>
        internal static string UseHalfMoon {
            get {
                return ResourceManager.GetString("UseHalfMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Thrusting. 的本地化字符串。
        /// </summary>
        internal static string UseThrusting {
            get {
                return ResourceManager.GetString("UseThrusting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warrior 的本地化字符串。
        /// </summary>
        internal static string Warrior {
            get {
                return ResourceManager.GetString("Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WarWizTao 的本地化字符串。
        /// </summary>
        internal static string WarWizTao {
            get {
                return ResourceManager.GetString("WarWizTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wizard 的本地化字符串。
        /// </summary>
        internal static string Wizard {
            get {
                return ResourceManager.GetString("Wizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You already have a Mentor. 的本地化字符串。
        /// </summary>
        internal static string YouAlreadyHaveAMentor {
            get {
                return ResourceManager.GetString("YouAlreadyHaveAMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re already married. 的本地化字符串。
        /// </summary>
        internal static string YouAreAlreadyMarried {
            get {
                return ResourceManager.GetString("YouAreAlreadyMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You&apos;re not married. 的本地化字符串。
        /// </summary>
        internal static string YouAreNotMarried {
            get {
                return ResourceManager.GetString("YouAreNotMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot cast {0} for another {1} seconds. 的本地化字符串。
        /// </summary>
        internal static string YouCannotCastForAnotherSeconds {
            get {
                return ResourceManager.GetString("YouCannotCastForAnotherSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must be wearing a suitable weapon to perform this skill. 的本地化字符串。
        /// </summary>
        internal static string YouMustBeWearingAsuitableWeaponToPerformThisSkill {
            get {
                return ResourceManager.GetString("YouMustBeWearingAsuitableWeaponToPerformThisSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your character was created successfully. 的本地化字符串。
        /// </summary>
        internal static string YourCharacterWasCreatedSuccessfully {
            get {
                return ResourceManager.GetString("YourCharacterWasCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your character was deleted successfully. 的本地化字符串。
        /// </summary>
        internal static string YourCharacterWasDeletedSuccessfully {
            get {
                return ResourceManager.GetString("YourCharacterWasDeletedSuccessfully", resourceCulture);
            }
        }
    }
}
