//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCharStat1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCharStat1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceCharStat1", typeof(ResourceCharStat1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AC 的本地化字符串。
        /// </summary>
        internal static string AC {
            get {
                return ResourceManager.GetString("AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accuracy 的本地化字符串。
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agility 的本地化字符串。
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attack Speed 的本地化字符串。
        /// </summary>
        internal static string AttackSpeed {
            get {
                return ResourceManager.GetString("AttackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crit Damage 的本地化字符串。
        /// </summary>
        internal static string CritDamage {
            get {
                return ResourceManager.GetString("CritDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crit Rate 的本地化字符串。
        /// </summary>
        internal static string CritRate {
            get {
                return ResourceManager.GetString("CritRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DC 的本地化字符串。
        /// </summary>
        internal static string DC {
            get {
                return ResourceManager.GetString("DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Health Points 的本地化字符串。
        /// </summary>
        internal static string HealthPoints {
            get {
                return ResourceManager.GetString("HealthPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Luck 的本地化字符串。
        /// </summary>
        internal static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AMC 的本地化字符串。
        /// </summary>
        internal static string MAC {
            get {
                return ResourceManager.GetString("MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mana Points 的本地化字符串。
        /// </summary>
        internal static string ManaPoints {
            get {
                return ResourceManager.GetString("ManaPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MC 的本地化字符串。
        /// </summary>
        internal static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SC 的本地化字符串。
        /// </summary>
        internal static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
    }
}
