//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceItemType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceItemType() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceItemType", typeof(ResourceItemType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Amulet 的本地化字符串。
        /// </summary>
        internal static string ItemTypeAmulet {
            get {
                return ResourceManager.GetString("ItemTypeAmulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Armour 的本地化字符串。
        /// </summary>
        internal static string ItemTypeArmour {
            get {
                return ResourceManager.GetString("ItemTypeArmour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awakening 的本地化字符串。
        /// </summary>
        internal static string ItemTypeAwakening {
            get {
                return ResourceManager.GetString("ItemTypeAwakening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bait 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBait {
            get {
                return ResourceManager.GetString("ItemTypeBait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bells 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBells {
            get {
                return ResourceManager.GetString("ItemTypeBells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Belt 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBelt {
            get {
                return ResourceManager.GetString("ItemTypeBelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Book 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBook {
            get {
                return ResourceManager.GetString("ItemTypeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boots 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBoots {
            get {
                return ResourceManager.GetString("ItemTypeBoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bracelet 的本地化字符串。
        /// </summary>
        internal static string ItemTypeBracelet {
            get {
                return ResourceManager.GetString("ItemTypeBracelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CraftingMaterial 的本地化字符串。
        /// </summary>
        internal static string ItemTypeCraftingMaterial {
            get {
                return ResourceManager.GetString("ItemTypeCraftingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deco 的本地化字符串。
        /// </summary>
        internal static string ItemTypeDeco {
            get {
                return ResourceManager.GetString("ItemTypeDeco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finder 的本地化字符串。
        /// </summary>
        internal static string ItemTypeFinder {
            get {
                return ResourceManager.GetString("ItemTypeFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fish 的本地化字符串。
        /// </summary>
        internal static string ItemTypeFish {
            get {
                return ResourceManager.GetString("ItemTypeFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Float 的本地化字符串。
        /// </summary>
        internal static string ItemTypeFloat {
            get {
                return ResourceManager.GetString("ItemTypeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Food 的本地化字符串。
        /// </summary>
        internal static string ItemTypeFood {
            get {
                return ResourceManager.GetString("ItemTypeFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gem 的本地化字符串。
        /// </summary>
        internal static string ItemTypeGem {
            get {
                return ResourceManager.GetString("ItemTypeGem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Helmet 的本地化字符串。
        /// </summary>
        internal static string ItemTypeHelmet {
            get {
                return ResourceManager.GetString("ItemTypeHelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hook 的本地化字符串。
        /// </summary>
        internal static string ItemTypeHook {
            get {
                return ResourceManager.GetString("ItemTypeHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mask 的本地化字符串。
        /// </summary>
        internal static string ItemTypeMask {
            get {
                return ResourceManager.GetString("ItemTypeMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meat 的本地化字符串。
        /// </summary>
        internal static string ItemTypeMeat {
            get {
                return ResourceManager.GetString("ItemTypeMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mount 的本地化字符串。
        /// </summary>
        internal static string ItemTypeMount {
            get {
                return ResourceManager.GetString("ItemTypeMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Necklace 的本地化字符串。
        /// </summary>
        internal static string ItemTypeNecklace {
            get {
                return ResourceManager.GetString("ItemTypeNecklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ore 的本地化字符串。
        /// </summary>
        internal static string ItemTypeOre {
            get {
                return ResourceManager.GetString("ItemTypeOre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pets 的本地化字符串。
        /// </summary>
        internal static string ItemTypePets {
            get {
                return ResourceManager.GetString("ItemTypePets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Potion 的本地化字符串。
        /// </summary>
        internal static string ItemTypePotion {
            get {
                return ResourceManager.GetString("ItemTypePotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quest 的本地化字符串。
        /// </summary>
        internal static string ItemTypeQuest {
            get {
                return ResourceManager.GetString("ItemTypeQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reel 的本地化字符串。
        /// </summary>
        internal static string ItemTypeReel {
            get {
                return ResourceManager.GetString("ItemTypeReel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reins 的本地化字符串。
        /// </summary>
        internal static string ItemTypeReins {
            get {
                return ResourceManager.GetString("ItemTypeReins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ribbon 的本地化字符串。
        /// </summary>
        internal static string ItemTypeRibbon {
            get {
                return ResourceManager.GetString("ItemTypeRibbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ring 的本地化字符串。
        /// </summary>
        internal static string ItemTypeRing {
            get {
                return ResourceManager.GetString("ItemTypeRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saddle 的本地化字符串。
        /// </summary>
        internal static string ItemTypeSaddle {
            get {
                return ResourceManager.GetString("ItemTypeSaddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script 的本地化字符串。
        /// </summary>
        internal static string ItemTypeScript {
            get {
                return ResourceManager.GetString("ItemTypeScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scroll 的本地化字符串。
        /// </summary>
        internal static string ItemTypeScroll {
            get {
                return ResourceManager.GetString("ItemTypeScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stone 的本地化字符串。
        /// </summary>
        internal static string ItemTypeStone {
            get {
                return ResourceManager.GetString("ItemTypeStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Torch 的本地化字符串。
        /// </summary>
        internal static string ItemTypeTorch {
            get {
                return ResourceManager.GetString("ItemTypeTorch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transform 的本地化字符串。
        /// </summary>
        internal static string ItemTypeTransform {
            get {
                return ResourceManager.GetString("ItemTypeTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon 的本地化字符串。
        /// </summary>
        internal static string ItemTypeWeapon {
            get {
                return ResourceManager.GetString("ItemTypeWeapon", resourceCulture);
            }
        }
    }
}
