//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceItemInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceItemInfo() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resources.ResourceItemInfo", typeof(ResourceItemInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Adds 的本地化字符串。
        /// </summary>
        internal static string Adds {
            get {
                return ResourceManager.GetString("Adds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amulet 的本地化字符串。
        /// </summary>
        internal static string Amulet {
            get {
                return ResourceManager.GetString("Amulet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Armour 的本地化字符串。
        /// </summary>
        internal static string Armour {
            get {
                return ResourceManager.GetString("Armour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BagWeight 的本地化字符串。
        /// </summary>
        internal static string BagWeight {
            get {
                return ResourceManager.GetString("BagWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Belt 的本地化字符串。
        /// </summary>
        internal static string Belt {
            get {
                return ResourceManager.GetString("Belt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boots 的本地化字符串。
        /// </summary>
        internal static string Boots {
            get {
                return ResourceManager.GetString("Boots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bracelet 的本地化字符串。
        /// </summary>
        internal static string Bracelet {
            get {
                return ResourceManager.GetString("Bracelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Breaks on death 的本地化字符串。
        /// </summary>
        internal static string BreaksOnDeath {
            get {
                return ResourceManager.GetString("BreaksOnDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can be used on: 的本地化字符串。
        /// </summary>
        internal static string CanBeUsedOn {
            get {
                return ResourceManager.GetString("CanBeUsedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Candle 的本地化字符串。
        /// </summary>
        internal static string Candle {
            get {
                return ResourceManager.GetString("Candle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot be a weddingring 的本地化字符串。
        /// </summary>
        internal static string CannotBeAWeddingring {
            get {
                return ResourceManager.GetString("CannotBeAWeddingring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot be used on any item. 的本地化字符串。
        /// </summary>
        internal static string CannotBeUsedOnAnyItem {
            get {
                return ResourceManager.GetString("CannotBeUsedOnAnyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t awaken 的本地化字符串。
        /// </summary>
        internal static string CantAwaken {
            get {
                return ResourceManager.GetString("CantAwaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t drop 的本地化字符串。
        /// </summary>
        internal static string CantDrop {
            get {
                return ResourceManager.GetString("CantDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t drop on death 的本地化字符串。
        /// </summary>
        internal static string CantDropOnDeath {
            get {
                return ResourceManager.GetString("CantDropOnDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t repair 的本地化字符串。
        /// </summary>
        internal static string CantRepair {
            get {
                return ResourceManager.GetString("CantRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t special repair 的本地化字符串。
        /// </summary>
        internal static string CantSpecialRepair {
            get {
                return ResourceManager.GetString("CantSpecialRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t store 的本地化字符串。
        /// </summary>
        internal static string CantStore {
            get {
                return ResourceManager.GetString("CantStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t trade 的本地化字符串。
        /// </summary>
        internal static string CantTrade {
            get {
                return ResourceManager.GetString("CantTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t upgrade 的本地化字符串。
        /// </summary>
        internal static string CantUpgrade {
            get {
                return ResourceManager.GetString("CantUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Chance 的本地化字符串。
        /// </summary>
        internal static string CriticalChance {
            get {
                return ResourceManager.GetString("CriticalChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Damage 的本地化字符串。
        /// </summary>
        internal static string CriticalDamage {
            get {
                return ResourceManager.GetString("CriticalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destroyed when dropped 的本地化字符串。
        /// </summary>
        internal static string DestroyedWhenDropped {
            get {
                return ResourceManager.GetString("DestroyedWhenDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop 的本地化字符串。
        /// </summary>
        internal static string Drop {
            get {
                return ResourceManager.GetString("Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Durability 的本地化字符串。
        /// </summary>
        internal static string Durability {
            get {
                return ResourceManager.GetString("Durability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp 的本地化字符串。
        /// </summary>
        internal static string Exp {
            get {
                return ResourceManager.GetString("Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expires in 的本地化字符串。
        /// </summary>
        internal static string ExpiresIn {
            get {
                return ResourceManager.GetString("ExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Health Recovery 的本地化字符串。
        /// </summary>
        internal static string HealthRecovery {
            get {
                return ResourceManager.GetString("HealthRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Helmet 的本地化字符串。
        /// </summary>
        internal static string Helmet {
            get {
                return ResourceManager.GetString("Helmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold CTRL and left click to combine with an item. 的本地化字符串。
        /// </summary>
        internal static string HoldCTRLAndLeftClickToCombineWithAnItem {
            get {
                return ResourceManager.GetString("HoldCTRLAndLeftClickToCombineWithAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold CTRL and left click to repair armour\nand accessory items. 的本地化字符串。
        /// </summary>
        internal static string HoldCTRLAndLeftClickToRepairArmourAndAccessoryItems {
            get {
                return ResourceManager.GetString("HoldCTRLAndLeftClickToRepairArmourAndAccessoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold CTRL and left click to repair weapons. 的本地化字符串。
        /// </summary>
        internal static string HoldCTRLAndLeftClickToRepairWeapons {
            get {
                return ResourceManager.GetString("HoldCTRLAndLeftClickToRepairWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item rented from 的本地化字符串。
        /// </summary>
        internal static string ItemRentedFrom {
            get {
                return ResourceManager.GetString("ItemRentedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loyalty 的本地化字符串。
        /// </summary>
        internal static string Loyalty {
            get {
                return ResourceManager.GetString("Loyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max HP 的本地化字符串。
        /// </summary>
        internal static string MaxHP {
            get {
                return ResourceManager.GetString("MaxHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max MP 的本地化字符串。
        /// </summary>
        internal static string MaxMP {
            get {
                return ResourceManager.GetString("MaxMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Necklace 的本地化字符串。
        /// </summary>
        internal static string Necklace {
            get {
                return ResourceManager.GetString("Necklace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nutrition 的本地化字符串。
        /// </summary>
        internal static string Nutrition {
            get {
                return ResourceManager.GetString("Nutrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purity 的本地化字符串。
        /// </summary>
        internal static string Purity {
            get {
                return ResourceManager.GetString("Purity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 的本地化字符串。
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reflect chance: {0} 的本地化字符串。
        /// </summary>
        internal static string ReflectChance {
            get {
                return ResourceManager.GetString("ReflectChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rental expires in 的本地化字符串。
        /// </summary>
        internal static string RentalExpiresIn {
            get {
                return ResourceManager.GetString("RentalExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rental lock expires in 的本地化字符串。
        /// </summary>
        internal static string RentalLockExpiresIn {
            get {
                return ResourceManager.GetString("RentalLockExpiresIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ring 的本地化字符串。
        /// </summary>
        internal static string Ring {
            get {
                return ResourceManager.GetString("Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soulbinds on equip 的本地化字符串。
        /// </summary>
        internal static string SoulbindsOnEquip {
            get {
                return ResourceManager.GetString("SoulbindsOnEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Soulbound to:  的本地化字符串。
        /// </summary>
        internal static string SoulboundTo {
            get {
                return ResourceManager.GetString("SoulboundTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stone 的本地化字符串。
        /// </summary>
        internal static string Stone {
            get {
                return ResourceManager.GetString("Stone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage 的本地化字符串。
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon 的本地化字符串。
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weight 的本地化字符串。
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
